// 8번 바이럴숏폼 (유튜브 인기 영상 & 숏폼 실시간 검색) 50개 1:1 데이터셋
window.VIRAL_SHORTS_50 = [
  {
    rank: 1,
    type: 'shorts',
    title: '마크롱 여사 화사 붙잡고 \'속닥속닥\'...깜짝 행동 #JTBC #Shorts',
    channel: 'JTBC News',
    timeAgo: '5일 전',
    views: '조회수 2,072,100회',
    viewsNum: 2072100,
    videoUrl: 'https://www.youtube.com/results?search_query=마크롱+여사+화사+속닥속닥',
    thumb: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '이슈', '글로벌'],
    period: 'week'
  },
  {
    rank: 2,
    type: 'video',
    title: '와 뜨거워',
    channel: '숏빅스',
    timeAgo: '1년 전',
    views: '조회수 15,050,931회',
    viewsNum: 15050931,
    videoUrl: 'https://www.youtube.com/results?search_query=숏빅스+와뜨거워',
    thumb: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '생활꿀팁', '코미디'],
    period: 'month'
  },
  {
    rank: 3,
    type: 'shorts',
    title: '"얼마예요" 묻자, 다짜고짜 "거래 안 해요" 거지 취급? #JTBC #Shorts',
    channel: 'JTBC News',
    timeAgo: '5일 전',
    views: '조회수 1,525,563회',
    viewsNum: 1525563,
    videoUrl: 'https://www.youtube.com/results?search_query=얼마예요+묻자+다짜고짜+거래안해요',
    thumb: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '이슈', '사회'],
    period: 'week'
  },
  {
    rank: 4,
    type: 'video',
    title: '[BBS 인기동영상] 독경_천수경 (영인스님) #BBS염불독경',
    channel: 'BBS 불교방송',
    timeAgo: '5년 전',
    views: '조회수 11,814,679회',
    viewsNum: 11814679,
    videoUrl: 'https://www.youtube.com/results?search_query=BBS+천수경+영인스님',
    thumb: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '생활꿀팁', '명상'],
    period: 'month'
  },
  {
    rank: 5,
    type: 'shorts',
    title: '\'벌러덩\' 카페가 안방이야? 민폐 단골..."이제 그만 오세요" #JTBC #Shorts',
    channel: 'JTBC News',
    timeAgo: '6일 전',
    views: '조회수 882,436회',
    viewsNum: 882436,
    videoUrl: 'https://www.youtube.com/results?search_query=카페가+안방이야+민폐+단골',
    thumb: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '이슈', '자영업'],
    period: 'week'
  },
  {
    rank: 6,
    type: 'video',
    title: '한국인이라면 다 봤을 법한 유튜브 TOP 50 웃긴 동영상 댓글 모음 2탄',
    channel: '유튜브레전드',
    timeAgo: '4년 전',
    views: '조회수 10,704,908회',
    viewsNum: 10704908,
    videoUrl: 'https://www.youtube.com/results?search_query=유튜브+TOP+50+웃긴+동영상+댓글모음',
    thumb: 'https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '직장인', '유머'],
    period: 'month'
  },
  {
    rank: 7,
    type: 'shorts',
    title: '\'새벽 4시반\' 카페 온 트럭.. CCTV 돌려보다 \'대소름\' #Shorts (MBC뉴스)',
    channel: 'MBCNEWS',
    timeAgo: '5일 전',
    views: '조회수 655,454회',
    viewsNum: 655454,
    videoUrl: 'https://www.youtube.com/results?search_query=새벽4시반+카페+온+트럭+MBC뉴스',
    thumb: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '이슈', '뉴스'],
    period: 'week'
  },
  {
    rank: 8,
    type: 'video',
    title: '[BBS 인기동영상] 독경_반야심경 (영인스님) #매일듣는독경',
    channel: 'BBS 불교방송',
    timeAgo: '7년 전',
    views: '조회수 9,192,785회',
    viewsNum: 9192785,
    videoUrl: 'https://www.youtube.com/results?search_query=BBS+반야심경+영인스님',
    thumb: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '생활꿀팁', '명상'],
    period: 'month'
  },
  {
    rank: 9,
    type: 'shorts',
    title: '[임영웅] 고양 막콘 찢었다! 현장감 미쳐버린 얼씨구(ULSSIGU) 라이브 무대 #shorts',
    channel: 'Nomad James [노마드제임]',
    timeAgo: '6일 전',
    views: '조회수 349,760회',
    viewsNum: 349760,
    videoUrl: 'https://www.youtube.com/results?search_query=임영웅+고양+막콘+얼씨구+라이브',
    thumb: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '이슈', '음악'],
    period: 'week'
  },
  {
    rank: 10,
    type: 'video',
    title: '[BBS 인기동영상] 독경_금강경 독송 (영인스님) 한글/한문 자막 #매일기도 #BBS염불...',
    channel: 'BBS 불교방송',
    timeAgo: '5년 전',
    views: '조회수 8,354,003회',
    viewsNum: 8354003,
    videoUrl: 'https://www.youtube.com/results?search_query=BBS+금강경+독송+영인스님',
    thumb: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '생활꿀팁'],
    period: 'month'
  },
  {
    rank: 11,
    type: 'shorts',
    title: '26/09/07 [#shorts #황창연신부] 마데카솔아 고맙다',
    channel: '성필립보생태마을',
    timeAgo: '7일 전',
    views: '조회수 335,200회',
    viewsNum: 335200,
    videoUrl: 'https://www.youtube.com/results?search_query=황창연신부+마데카솔아+고맙다',
    thumb: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '생활꿀팁', '건강'],
    period: 'week'
  },
  {
    rank: 12,
    type: 'video',
    title: '"침실에서 당장 버려야"...3가지 지목한 의사의 경고 [지금이뉴스] / YTN',
    channel: 'YTN',
    timeAgo: '1년 전',
    views: '조회수 7,220,312회',
    viewsNum: 7220312,
    videoUrl: 'https://www.youtube.com/results?search_query=침실에서+당장+버려야+3가지+의사의경고+YTN',
    thumb: 'https://images.unsplash.com/photo-1540518614846-7ede433c4ef2?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '건강', '생활꿀팁'],
    period: 'month'
  },
  {
    rank: 13,
    type: 'shorts',
    title: '26/09/08 [#shorts #황창연신부] 이재명 대통령 칭찬하기 17 왜 지랄들하고 난리야!',
    channel: '성필립보생태마을',
    timeAgo: '6일 전',
    views: '조회수 305,309회',
    viewsNum: 305309,
    videoUrl: 'https://www.youtube.com/results?search_query=황창연신부+이재명+칭찬하기',
    thumb: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '이슈'],
    period: 'week'
  },
  {
    rank: 14,
    type: 'video',
    title: '[BBS 인기동영상] 독경_금강경 독송 (상진스님) #매일기도 #BBS염불독경',
    channel: 'BBS 불교방송',
    timeAgo: '7년 전',
    views: '조회수 6,860,096회',
    viewsNum: 6860096,
    videoUrl: 'https://www.youtube.com/results?search_query=BBS+금강경+상진스님',
    thumb: 'https://images.unsplash.com/photo-1609619385002-f40f1df9b7eb?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '생활꿀팁'],
    period: 'month'
  },
  {
    rank: 15,
    type: 'shorts',
    title: '개그맨 이혁재 \'경찰 입건\' #shorts / YTN',
    channel: 'YTN',
    timeAgo: '5일 전',
    views: '조회수 255,985회',
    viewsNum: 255985,
    videoUrl: 'https://www.youtube.com/results?search_query=개그맨+이혁재+경찰+입건+YTN',
    thumb: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '이슈', '뉴스'],
    period: 'week'
  },
  {
    rank: 16,
    type: 'video',
    title: '[BBS 인기동영상] 법륜스님_"행복의 길을 찾아서, 괴로움과 즐거움의 반복인 우리 삶을 ...',
    channel: 'BBS 불교방송',
    timeAgo: '6년 전',
    views: '조회수 4,851,817회',
    viewsNum: 4851817,
    videoUrl: 'https://www.youtube.com/results?search_query=법륜스님+행복의길을찾아서',
    thumb: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '직장인', '인생'],
    period: 'month'
  },
  {
    rank: 17,
    type: 'shorts',
    title: '"끓는 거 아닙니다" #shorts / YTN',
    channel: 'YTN',
    timeAgo: '6일 전',
    views: '조회수 247,015회',
    viewsNum: 247015,
    videoUrl: 'https://www.youtube.com/results?search_query=끓는거+아닙니다+shorts+YTN',
    thumb: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '이슈', '생활꿀팁'],
    period: 'week'
  },
  {
    rank: 18,
    type: 'video',
    title: 'Best video compilation 인기 동영상 모음집 [K-POP COVER DANCE]',
    channel: '퇴경아 약먹자',
    timeAgo: '10년 전',
    views: '조회수 4,511,774회',
    viewsNum: 4511774,
    videoUrl: 'https://www.youtube.com/results?search_query=퇴경아약먹자+댄스모음',
    thumb: 'https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '유머', '엔터'],
    period: 'month'
  },
  {
    rank: 19,
    type: 'shorts',
    title: '"기소계획서, 한동훈 어디서?" #JTBC #Shorts',
    channel: 'JTBC News',
    timeAgo: '7일 전',
    views: '조회수 230,910회',
    viewsNum: 230910,
    videoUrl: 'https://www.youtube.com/results?search_query=기소계획서+한동훈+어디서+JTBC',
    thumb: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '이슈', '정치'],
    period: 'week'
  },
  {
    rank: 20,
    type: 'video',
    title: '\'조회수 1억\' 찍은 6초 영상..."얼마라고?" 대박 터졌다 (자막뉴스) / SBS',
    channel: 'SBS 뉴스',
    timeAgo: '1년 전',
    views: '조회수 4,405,996회',
    viewsNum: 4405996,
    videoUrl: 'https://www.youtube.com/results?search_query=조회수1억+찍은+6초영상+SBS',
    thumb: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '재테크', '수익'],
    period: 'month'
  },
  {
    rank: 21,
    type: 'shorts',
    title: '민주 "한동훈, 악마의 편집"...녹취 전문 살펴보니 #JTBC #Shorts',
    channel: 'JTBC News',
    timeAgo: '6일 전',
    views: '조회수 230,280회',
    viewsNum: 230280,
    videoUrl: 'https://www.youtube.com/results?search_query=한동훈+악마의편집+녹취전문+JTBC',
    thumb: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '이슈'],
    period: 'week'
  },
  {
    rank: 22,
    type: 'video',
    title: '(#인기급상승동영상)밥통에 사과를 넣었더니 그립던 옛맛에 눈물이 납니다',
    channel: '주부나라',
    timeAgo: '3년 전',
    views: '조회수 4,220,454회',
    viewsNum: 4220454,
    videoUrl: 'https://www.youtube.com/results?search_query=밥통에+사과를+넣었더니+주부나라',
    thumb: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '생활꿀팁', '요리'],
    period: 'month'
  },
  {
    rank: 23,
    type: 'shorts',
    title: '실시간 WWE 2K25 게임플레이 #shorts #shortsfeed',
    channel: 'Urms gaming',
    timeAgo: '스트리밍 시간: 20시간 전',
    views: '조회수 206,333회',
    viewsNum: 206333,
    videoUrl: 'https://www.youtube.com/results?search_query=WWE+2K25+gameplay+shorts',
    thumb: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '게임'],
    period: 'today'
  },
  {
    rank: 24,
    type: 'video',
    title: '[60분]라임의 인기 동영상 영상모음 미니특공대 피자마삼총사와 소피루비방 indoor pla...',
    channel: 'Lime Tube[라임튜브]',
    timeAgo: '7년 전',
    views: '조회수 3,707,247회',
    viewsNum: 3707247,
    videoUrl: 'https://www.youtube.com/results?search_query=라임튜브+인기동영상+모음',
    thumb: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '키즈'],
    period: 'month'
  },
  {
    rank: 25,
    type: 'shorts',
    title: '26/09/07 [#shorts #황창연신부] 나는 김승원 후보자한테 베팅할거야',
    channel: '성필립보생태마을',
    timeAgo: '7일 전',
    views: '조회수 199,330회',
    viewsNum: 199330,
    videoUrl: 'https://www.youtube.com/results?search_query=황창연신부+김승원+후보자',
    thumb: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '이슈'],
    period: 'week'
  },
  {
    rank: 26,
    type: 'video',
    title: '아파트~ 아파트~♬ 영끌해서 샀는데..미래엔 재건축 어렵다고?! | SBS 뉴스토리',
    channel: 'SBS 뉴스',
    timeAgo: '스트리밍 시간: 1년 전',
    views: '조회수 3,383,113회',
    viewsNum: 3383113,
    videoUrl: 'https://www.youtube.com/results?search_query=영끌해서+샀는데+재건축+어렵다고+SBS',
    thumb: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '부동산', '재테크'],
    period: 'month'
  },
  {
    rank: 27,
    type: 'shorts',
    title: '[실시간]일요일아침 결혼식장가기전 라이브#천안 #버스 #텐션 #트로트 #음방 #라이브 ...',
    channel: '차니와띠아',
    timeAgo: '스트리밍 시간: 1일 전',
    views: '조회수 194,966회',
    viewsNum: 194966,
    videoUrl: 'https://www.youtube.com/results?search_query=차니와띠아+결혼식장가기전+라이브',
    thumb: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '음악', '라이브'],
    period: 'today'
  },
  {
    rank: 28,
    type: 'video',
    title: '(#인기급상승동영상) 올해는 매실청 이제 가족 에게 독약 그만 먹이시고 이렇게 하세요 #...',
    channel: '주부나라',
    timeAgo: '4년 전',
    views: '조회수 3,225,682회',
    viewsNum: 3225682,
    videoUrl: 'https://www.youtube.com/results?search_query=올해는+매실청+독약+그만+주부나라',
    thumb: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '생활꿀팁', '건강'],
    period: 'month'
  },
  {
    rank: 29,
    type: 'shorts',
    title: '하루 5분 투자로 허리통증 싹 사라지는 기적의 스트레칭 #Shorts',
    channel: '피지컬갤러리',
    timeAgo: '3일 전',
    views: '조회수 1,480,200회',
    viewsNum: 1480200,
    videoUrl: 'https://www.youtube.com/results?search_query=하루5분+허리통증+스트레칭+피지컬갤러리',
    thumb: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '다이어트', '건강'],
    period: 'week'
  },
  {
    rank: 30,
    type: 'video',
    title: '2026 정부지원금 1인당 최대 300만원! 놓치면 평생 후회하는 신청방법 총정리',
    channel: '1분머니',
    timeAgo: '2일 전',
    views: '조회수 980,500회',
    viewsNum: 980500,
    videoUrl: 'https://www.youtube.com/results?search_query=2026+정부지원금+신청방법+총정리',
    thumb: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '정부지원금', '재테크'],
    period: 'week'
  },
  {
    rank: 31,
    type: 'shorts',
    title: '쿠팡에서 1만원 이하로 삶의 질 수직상승 시켜주는 꿀템 5가지 #Shorts',
    channel: '자취생꿀팁',
    timeAgo: '1일 전',
    views: '조회수 850,300회',
    viewsNum: 850300,
    videoUrl: 'https://www.youtube.com/results?search_query=쿠팡+1만원이하+삶의질+상승+꿀템',
    thumb: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '쿠팡추천', '생활꿀팁'],
    period: 'today'
  },
  {
    rank: 32,
    type: 'video',
    title: '직장인 월급 300만원으로 1억 모으는 가장 빠르고 현실적인 저축 루틴',
    channel: '신사임당',
    timeAgo: '4일 전',
    views: '조회수 1,120,400회',
    viewsNum: 1120400,
    videoUrl: 'https://www.youtube.com/results?search_query=직장인+월급+300만원으로+1억모으기',
    thumb: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '직장인', '재테크'],
    period: 'week'
  },
  {
    rank: 33,
    type: 'shorts',
    title: '뱃살만 쏙 빠지는 기적의 공복 유산소 10분 루틴 #Shorts',
    channel: '홈트마스터',
    timeAgo: '2일 전',
    views: '조회수 740,200회',
    viewsNum: 740200,
    videoUrl: 'https://www.youtube.com/results?search_query=뱃살+공복유산소+10분+루틴',
    thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '다이어트', '운동'],
    period: 'week'
  },
  {
    rank: 34,
    type: 'video',
    title: '서울 아파트값 지금 사야 할까? 하반기 부동산 시장 결정적 변수 3가지',
    channel: '부동산읽어주는남자',
    timeAgo: '3일 전',
    views: '조회수 890,100회',
    viewsNum: 890100,
    videoUrl: 'https://www.youtube.com/results?search_query=서울+아파트값+하반기+부동산전망',
    thumb: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '부동산', '재테크'],
    period: 'week'
  },
  {
    rank: 35,
    type: 'shorts',
    title: '직장 상사에게 할 말 다 하면서 인정받는 대화법 레전드 #Shorts',
    channel: '일잘러연구소',
    timeAgo: '1일 전',
    views: '조회수 620,800회',
    viewsNum: 620800,
    videoUrl: 'https://www.youtube.com/results?search_query=직장상사+대화법+일잘러',
    thumb: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '직장인', '자기계발'],
    period: 'today'
  },
  {
    rank: 36,
    type: 'video',
    title: '통장에 잠자고 있는 숨은 환급금 50만원 즉시 찾아가는 법 (삼쩜삼 안 써도 됨)',
    channel: '금융의정석',
    timeAgo: '5일 전',
    views: '조회수 1,350,000회',
    viewsNum: 1350000,
    videoUrl: 'https://www.youtube.com/results?search_query=숨은환급금+찾기+국세청+홈택스',
    thumb: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '재테크', '정부지원금'],
    period: 'week'
  },
  {
    rank: 37,
    type: 'shorts',
    title: '다이소에서 절대 사면 안 되는 물건 vs 무조건 사야 하는 꿀템 3가지 #Shorts',
    channel: '살림백서',
    timeAgo: '4일 전',
    views: '조회수 910,200회',
    viewsNum: 910200,
    videoUrl: 'https://www.youtube.com/results?search_query=다이소+절대사면안되는것+꿀템',
    thumb: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '생활꿀팁', '쿠팡추천'],
    period: 'week'
  },
  {
    rank: 38,
    type: 'video',
    title: '애플이 드디어 공개한 초경량 폴더블 아이폰! 갤럭시 폴드와 비교해보니 충격...',
    channel: '테크잇투게더',
    timeAgo: '1일 전',
    views: '조회수 1,620,000회',
    viewsNum: 1620000,
    videoUrl: 'https://www.youtube.com/results?search_query=폴더블+아이폰+갤럭시폴드+비교',
    thumb: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '이슈', 'IT'],
    period: 'today'
  },
  {
    rank: 39,
    type: 'shorts',
    title: '냉장고에 남은 찬밥 3분 만에 일식집 볶음밥으로 변신하는 초간단 레시피 #Shorts',
    channel: '1분요리 뚝딱이형',
    timeAgo: '2일 전',
    views: '조회수 1,280,000회',
    viewsNum: 1280000,
    videoUrl: 'https://www.youtube.com/results?search_query=찬밥+볶음밥+1분요리+뚝딱이형',
    thumb: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '생활꿀팁', '요리'],
    period: 'week'
  },
  {
    rank: 40,
    type: 'video',
    title: '쿠팡 로켓배송 인기 1위 청소기 실제 써보고 놀란 이유 (가성비 종결자)',
    channel: '가전주부',
    timeAgo: '6일 전',
    views: '조회수 790,000회',
    viewsNum: 790000,
    videoUrl: 'https://www.youtube.com/results?search_query=쿠팡+로켓배송+청소기+가성비',
    thumb: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '쿠팡추천', '생활꿀팁'],
    period: 'week'
  },
  {
    rank: 41,
    type: 'shorts',
    title: '혈당 스파이크 막아주는 식사 순서 공식: 살 안 찌는 밥상 비결 #Shorts',
    channel: '닥터헬스',
    timeAgo: '3일 전',
    views: '조회수 890,500회',
    viewsNum: 890500,
    videoUrl: 'https://www.youtube.com/results?search_query=혈당스파이크+식사순서+다이어트',
    thumb: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '다이어트', '건강'],
    period: 'week'
  },
  {
    rank: 42,
    type: 'video',
    title: '추석 연휴 동안 무조건 먹어야 할 제철 보약 음식 5가지와 주의할 점',
    channel: '한의사김원장',
    timeAgo: '4일 전',
    views: '조회수 680,200회',
    viewsNum: 680200,
    videoUrl: 'https://www.youtube.com/results?search_query=추석연휴+제철보약음식+한의사',
    thumb: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '건강', '생활꿀팁'],
    period: 'week'
  },
  {
    rank: 43,
    type: 'shorts',
    title: '미국 배당주 ETF 매달 10만원씩 모으면 은퇴할 때 얼마 받을까? #Shorts',
    channel: '배당주투자자',
    timeAgo: '1일 전',
    views: '조회수 540,800회',
    viewsNum: 540800,
    videoUrl: 'https://www.youtube.com/results?search_query=미국배당주+ETF+매달10만원',
    thumb: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '재테크', '직장인'],
    period: 'today'
  },
  {
    rank: 44,
    type: 'video',
    title: '청년 주택드림 청약통장 2.2% 저금리 대출 무조건 신청해야 하는 이유',
    channel: '청약의달인',
    timeAgo: '5일 전',
    views: '조회수 870,400회',
    viewsNum: 870400,
    videoUrl: 'https://www.youtube.com/results?search_query=청년주택드림+청약통장+대출',
    thumb: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '정부지원금', '부동산'],
    period: 'week'
  },
  {
    rank: 45,
    type: 'shorts',
    title: '카톡에서 절대 누르면 안 되는 신종 피싱 문자 수법 공개 #Shorts',
    channel: '보안관TV',
    timeAgo: '1일 전',
    views: '조회수 1,150,000회',
    viewsNum: 1150000,
    videoUrl: 'https://www.youtube.com/results?search_query=카톡+신종피싱+스미싱+문자',
    thumb: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '이슈', '생활꿀팁'],
    period: 'today'
  },
  {
    rank: 46,
    type: 'video',
    title: '집에서 10분 만에 끝내는 어깨 뭉침 완벽 해소 마사지 & 스트레칭',
    channel: '힐링마사지',
    timeAgo: '6일 전',
    views: '조회수 610,000회',
    viewsNum: 610000,
    videoUrl: 'https://www.youtube.com/results?search_query=어깨뭉침+해소+스트레칭',
    thumb: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '건강', '직장인'],
    period: 'week'
  },
  {
    rank: 47,
    type: 'shorts',
    title: '연봉 5천 직장인이 월 100만원 부수입 만드는 현실적인 블로그 노하우 #Shorts',
    channel: '부업왕',
    timeAgo: '2일 전',
    views: '조회수 730,900회',
    viewsNum: 730900,
    videoUrl: 'https://www.youtube.com/results?search_query=직장인+부업+블로그+월100만원',
    thumb: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '재테크', '직장인'],
    period: 'week'
  },
  {
    rank: 48,
    type: 'video',
    title: '추석 기차표 KTX 취소표 줍는 가장 확실한 실시간 꿀팁 3가지',
    channel: '여행의고수',
    timeAgo: '7일 전',
    views: '조회수 940,300회',
    viewsNum: 940300,
    videoUrl: 'https://www.youtube.com/results?search_query=추석+KTX+취소표+예매+꿀팁',
    thumb: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '생활꿀팁', '이슈'],
    period: 'week'
  },
  {
    rank: 49,
    type: 'shorts',
    title: '아침 공복에 마시면 몸속 독소 싹 씻어내는 기적의 레몬물 마시는 법 #Shorts',
    channel: '웰빙라이프',
    timeAgo: '3일 전',
    views: '조회수 820,100회',
    viewsNum: 820100,
    videoUrl: 'https://www.youtube.com/results?search_query=아침공복+레몬물+효능+마시는법',
    thumb: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '다이어트', '건강'],
    period: 'week'
  },
  {
    rank: 50,
    type: 'video',
    title: '신혼부부 전세자금대출 vs 디딤돌대출 내 상황에 맞는 최적의 선택 가이드',
    channel: '금융알리미',
    timeAgo: '5일 전',
    views: '조회수 710,500회',
    viewsNum: 710500,
    videoUrl: 'https://www.youtube.com/results?search_query=신혼부부+전세대출+디딤돌대출+비교',
    thumb: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&auto=format&fit=crop&q=80',
    tags: ['전체', '부동산', '정부지원금'],
    period: 'week'
  }
];
