/**
 * 8번 바이럴숏폼 (유튜브 실시간 바이럴 & 숏폼) 데이터셋
 * boutique-info 원본 실시간 API 데이터 1:1 완벽 일치 (각 50개)
 * 실제 유튜브 영상 직링크 (url: https://www.youtube.com/shorts/... 또는 watch?v=...)
 */

// 1. [당일 (오늘 24H)] 실시간 인기 & 화제 영상 50개
window.VIRAL_SHORTS_TODAY = [
  {
    rank: 1,
    id: 'w_7UWSjdvIs',
    type: 'shorts',
    title: 'LIVE WWE 2K25 Gameplay #shorts #shortsfeed',
    channel: 'Urms gaming',
    timeAgo: '스트리밍 시간: 12시간 전',
    views: '조회수 271,099회',
    viewsNum: 271099,
    videoUrl: 'https://www.youtube.com/shorts/w_7UWSjdvIs',
    thumb: 'https://i.ytimg.com/vi/w_7UWSjdvIs/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBKfGWe6xJmXIN_DNgzL4eLmLIH7g',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 2,
    id: '5faE7RCCF9U',
    type: 'video',
    title: '와 뜨거워',
    channel: '숏박스',
    timeAgo: '1년 전',
    views: '조회수 15,056,587회',
    viewsNum: 15056587,
    videoUrl: 'https://www.youtube.com/watch?v=5faE7RCCF9U',
    thumb: 'https://i.ytimg.com/vi/5faE7RCCF9U/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvzf0uyCq6TxtCXmiJQiSvUOp9YA',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 3,
    id: 'zcHvH_Unojs',
    type: 'shorts',
    title: '[실시간]버스똥꼬쇼(2부)!#천안 #버스 #텐션 #트로트 #음방 #라이브 #shorts',
    channel: '차니와띠아',
    timeAgo: '스트리밍 시간: 16시간 전',
    views: '조회수 90,789회',
    viewsNum: 90789,
    videoUrl: 'https://www.youtube.com/shorts/zcHvH_Unojs',
    thumb: 'https://i.ytimg.com/vi/zcHvH_Unojs/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCGBA9J7Ln25vMPk0pXaNJA3feYsg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 4,
    id: 'gPN0pYVZFW0',
    type: 'video',
    title: '2026년 9월 15일 알고리즘에 뜰 영상',
    channel: '스토리',
    timeAgo: '5년 전',
    views: '조회수 14,802,054회',
    viewsNum: 14802054,
    videoUrl: 'https://www.youtube.com/watch?v=gPN0pYVZFW0',
    thumb: 'https://i.ytimg.com/vi/gPN0pYVZFW0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAsSJBQKDfLf8hYdfXEamp97pREog',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 5,
    id: 'gbw1RtrAWO8',
    type: 'shorts',
    title: 'LIVE WWE 2K25 Gameplay #shorts #shortsfeed',
    channel: 'Urms gaming',
    timeAgo: '스트리밍 시간: 11시간 전',
    views: '조회수 84,714회',
    viewsNum: 84714,
    videoUrl: 'https://www.youtube.com/shorts/gbw1RtrAWO8',
    thumb: 'https://i.ytimg.com/vi/gbw1RtrAWO8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAvZamKW0YCuDloQEkxJXnT4lfImQ',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 6,
    id: 'R9O30wgdmw8',
    type: 'video',
    title: '[BBS 인기동영상] 독경_천수경 (영인스님) #BBS염불독경',
    channel: 'BBS 불교방송',
    timeAgo: '5년 전',
    views: '조회수 11,820,809회',
    viewsNum: 11820809,
    videoUrl: 'https://www.youtube.com/watch?v=R9O30wgdmw8',
    thumb: 'https://i.ytimg.com/vi/R9O30wgdmw8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCuLldNxH4I7Gouz5DYX5f0yWk7gA',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 7,
    id: '_OklvqrMNVI',
    type: 'shorts',
    title: 'WWE 2K25 LIVE GAMEPLAY | #wwe2k25 #live #livestream #shorts #shortsfeed #gaming',
    channel: 'WWE Zone',
    timeAgo: '스트리밍 시간: 12시간 전',
    views: '조회수 68,453회',
    viewsNum: 68453,
    videoUrl: 'https://www.youtube.com/shorts/_OklvqrMNVI',
    thumb: 'https://i.ytimg.com/vi/_OklvqrMNVI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCG2f6AbMDYx2J-DBAntPO5EKBHrg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 8,
    id: 'VuDY1PBAuWU',
    type: 'video',
    title: '한국인이라면 다 봤을 법한 유튜브 TOP 50 웃긴 동영상 댓글 모음 2탄',
    channel: '유튜브레전드',
    timeAgo: '4년 전',
    views: '조회수 10,706,890회',
    viewsNum: 10706890,
    videoUrl: 'https://www.youtube.com/watch?v=VuDY1PBAuWU',
    thumb: 'https://i.ytimg.com/vi/VuDY1PBAuWU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCKwyYpDE3pcieHaPl8cTLEWX1WbQ',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 9,
    id: 'Rq5CEql0DR4',
    type: 'shorts',
    title: '[실시간]배고파서ㅜㅜ!#천안 #버스 #텐션 #트로트 #음방 #라이브 #shorts',
    channel: '차니와띠아',
    timeAgo: '스트리밍 시간: 21시간 전',
    views: '조회수 57,429회',
    viewsNum: 57429,
    videoUrl: 'https://www.youtube.com/shorts/Rq5CEql0DR4',
    thumb: 'https://i.ytimg.com/vi/Rq5CEql0DR4/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCzyICeD7InvkSqNI08hkRsfp1ThQ',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 10,
    id: 'bTizqvC5X9o',
    type: 'video',
    title: '[BBS 인기동영상] 독경_반야심경 (영인스님) #매일듣는독경',
    channel: 'BBS 불교방송',
    timeAgo: '7년 전',
    views: '조회수 9,196,183회',
    viewsNum: 9196183,
    videoUrl: 'https://www.youtube.com/watch?v=bTizqvC5X9o',
    thumb: 'https://i.ytimg.com/vi/bTizqvC5X9o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCrIH-eap_vucJ0JfTQaxmawduuWA',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 11,
    id: 'Bq2Q4EtGlCo',
    type: 'shorts',
    title: '다 어디 갔어 ㅠㅠ #kpop #shorts #댄스 #리액션 #소통 #엑셀 #실시간 #BTS #채팅 #여행 #투깝이 #용국처럼 #용용이 #카광 #중검',
    channel: '요다찡',
    timeAgo: '스트리밍 시간: 13시간 전',
    views: '조회수 8,099회',
    viewsNum: 8099,
    videoUrl: 'https://www.youtube.com/shorts/Bq2Q4EtGlCo',
    thumb: 'https://i.ytimg.com/vi/Bq2Q4EtGlCo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBYrxnO7yM0FQVPTmBi-CYNAbxQDA',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 12,
    id: 'ge0bwN5U2-o',
    type: 'video',
    title: '[BBS 인기동영상] 독경_금강경 독송  (영인스님)  한글/한문 자막 #매일기도 #BBS염불독경',
    channel: 'BBS 불교방송',
    timeAgo: '5년 전',
    views: '조회수 8,357,015회',
    viewsNum: 8357015,
    videoUrl: 'https://www.youtube.com/watch?v=ge0bwN5U2-o',
    thumb: 'https://i.ytimg.com/vi/ge0bwN5U2-o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCB-1oEj-BZbKN4tmDEKZMFKYZwOQ',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 13,
    id: '2FAPjHjh7Es',
    type: 'shorts',
    title: '고전게임, 레트로(RETRO) 게임 실시간 26-09-14 라이브 #Shorts #쇼츠 #쇼츠라이브',
    channel: '게임은 관짜마',
    timeAgo: '스트리밍 시간: 7시간 전',
    views: '조회수 2,825회',
    viewsNum: 2825,
    videoUrl: 'https://www.youtube.com/shorts/2FAPjHjh7Es',
    thumb: 'https://i.ytimg.com/vi/2FAPjHjh7Es/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBWjP7Sbsxp73SSXZmjeFUEcv2HtA',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 14,
    id: 'rOydU8F_lio',
    type: 'video',
    title: '"침실에서 당장 버려야"...3가지 지목한 의사의 경고 [지금이뉴스] / YTN',
    channel: 'YTN',
    timeAgo: '1년 전',
    views: '조회수 7,231,343회',
    viewsNum: 7231343,
    videoUrl: 'https://www.youtube.com/watch?v=rOydU8F_lio',
    thumb: 'https://i.ytimg.com/vi/rOydU8F_lio/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCxdt5z-loWeWDV1PqEQGlA52AjhQ',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 15,
    id: 'TrUlqOjTX54',
    type: 'shorts',
    title: '주말의 흔적 | 노래하나얘기둘  #실시간 #소통 #live #shorts #라디오 #보이는라디오 260914',
    channel: 'KNN 라디오 센텀 수달',
    timeAgo: '스트리밍 시간: 15시간 전',
    views: '조회수 1,591회',
    viewsNum: 1591,
    videoUrl: 'https://www.youtube.com/shorts/TrUlqOjTX54',
    thumb: 'https://i.ytimg.com/vi/TrUlqOjTX54/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAQOM1PCJNurtyqx-jvwRU4WvlksQ',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 16,
    id: 'pFxM98oPGDc',
    type: 'video',
    title: '[BBS 인기동영상] 독경_금강경 독송 (상진스님)  #매일기도 #BBS염불독경',
    channel: 'BBS 불교방송',
    timeAgo: '7년 전',
    views: '조회수 6,861,503회',
    viewsNum: 6861503,
    videoUrl: 'https://www.youtube.com/watch?v=pFxM98oPGDc',
    thumb: 'https://i.ytimg.com/vi/pFxM98oPGDc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCxMGk-7-C6gC3BvQrjavoPj8C_AQ',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 17,
    id: 'g_Ic_cPfF7E',
    type: 'shorts',
    title: '[리니지클래식] 슬티비 화요일 #shorts #리니지클래식 #쇼츠라이브 #실시간방송 #코인 #주식 #삼성전자 #하이닉스  #엑셀방송',
    channel: 'jimimi',
    timeAgo: '스트리밍 시간: 1시간 전',
    views: '조회수 1,285회',
    viewsNum: 1285,
    videoUrl: 'https://www.youtube.com/shorts/g_Ic_cPfF7E',
    thumb: 'https://i.ytimg.com/vi/g_Ic_cPfF7E/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCw6Qp61btBhNxkfGjVFnGInNOdyg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 18,
    id: 'cItcwI3yd4M',
    type: 'video',
    title: '[BBS 인기동영상] 법륜스님_"행복의 길을 찾아서, 괴로움과 즐거움의 반복인 우리 삶을 어떻게 행복하게 살 것인가" #법륜스님토크콘서트 #행복의길',
    channel: 'BBS 불교방송',
    timeAgo: '6년 전',
    views: '조회수 4,852,694회',
    viewsNum: 4852694,
    videoUrl: 'https://www.youtube.com/watch?v=cItcwI3yd4M',
    thumb: 'https://i.ytimg.com/vi/cItcwI3yd4M/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDgbDaO_iUBgjjvcQAZCba7MogI1A',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 19,
    id: 'WWrZSvBj0f4',
    type: 'shorts',
    title: '[리니지클래식] 슬티비 #shorts #리니지클래식 #쇼츠라이브 #실시간방송 #코인 #주식 #삼성전자 #하이닉스  #엑셀방송',
    channel: 'ddooddo',
    timeAgo: '스트리밍 시간: 19분 전',
    views: '조회수 1,236회',
    viewsNum: 1236,
    videoUrl: 'https://www.youtube.com/shorts/WWrZSvBj0f4',
    thumb: 'https://i.ytimg.com/vi/WWrZSvBj0f4/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBzX8c6aiV-YjU4nZP5CTDt1EkzTw',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 20,
    id: 'NeNJ7wF8wHg',
    type: 'video',
    title: 'Best video compilation 인기 동영상 모음집 [K-POP COVER DANCE]',
    channel: '퇴경아 약먹자',
    timeAgo: '10년 전',
    views: '조회수 4,511,789회',
    viewsNum: 4511789,
    videoUrl: 'https://www.youtube.com/watch?v=NeNJ7wF8wHg',
    thumb: 'https://i.ytimg.com/vi/NeNJ7wF8wHg/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARh_IDYoLzAP&rs=AOn4CLDQl7alDhIRQXr4kX_593Za3h1zsQ',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 21,
    id: 'HPIWB1cXNq0',
    type: 'shorts',
    title: '[리니지클래식] 슬티비 #shorts #리니지클래식 #쇼츠라이브 #실시간방송 #코인 #주식 #삼성전자 #하이닉스  #엑셀방송',
    channel: 'doolidooli',
    timeAgo: '스트리밍 시간: 2시간 전',
    views: '조회수 1,009회',
    viewsNum: 1009,
    videoUrl: 'https://www.youtube.com/shorts/HPIWB1cXNq0',
    thumb: 'https://i.ytimg.com/vi/HPIWB1cXNq0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC0fCm520ZVySTCALOc6sO6xOjKGw',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 22,
    id: '2ku8q4ZYtOg',
    type: 'video',
    title: '\'조회수 1억\' 찍은 6초 영상…"얼마라고?" 대박 터졌다 (자막뉴스) / SBS',
    channel: 'SBS 뉴스',
    timeAgo: '1년 전',
    views: '조회수 4,406,820회',
    viewsNum: 4406820,
    videoUrl: 'https://www.youtube.com/watch?v=2ku8q4ZYtOg',
    thumb: 'https://i.ytimg.com/vi/2ku8q4ZYtOg/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC-uELr1L2UEimV8gA0d5txKaSQBQ',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 23,
    id: 'HtuiNaPgChE',
    type: 'shorts',
    title: 'BTS (KOREA) 🇰🇷 vs Harry Styles (UK) 🇬🇧 - Trending Top Globally!! #shorts',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 898회',
    viewsNum: 898,
    videoUrl: 'https://www.youtube.com/shorts/HtuiNaPgChE',
    thumb: 'https://i.ytimg.com/vi/HtuiNaPgChE/frame0.jpg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 24,
    id: '--m5TieGS6Y',
    type: 'video',
    title: '(#인기급상승동영상)밥통에 사과를 넣었더니 그립던 옛맛에 눈물이 납니다',
    channel: '주부나라',
    timeAgo: '3년 전',
    views: '조회수 4,220,507회',
    viewsNum: 4220507,
    videoUrl: 'https://www.youtube.com/watch?v=--m5TieGS6Y',
    thumb: 'https://i.ytimg.com/vi/--m5TieGS6Y/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCBJ5z2GnCL2llMfWE2ZGn7sa7gWA',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 25,
    id: 'ndBa2JbXpAA',
    type: 'shorts',
    title: '이케아 직원들도 몰래 사 간다는 레전드 도마 😱 #공간활용 #꿀팁 #살림꿀팁 #이케아 #좁은집인테리어  #쇼츠 #살림초보',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 835회',
    viewsNum: 835,
    videoUrl: 'https://www.youtube.com/shorts/ndBa2JbXpAA',
    thumb: 'https://i.ytimg.com/vi/ndBa2JbXpAA/frame0.jpg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 26,
    id: '3W9KANpIEzE',
    type: 'video',
    title: '[60분]라임의 인기 동영상 영상모음 미니특공대 파자마삼총사와 소피루비방 indoor playground fun for kids | johny johny',
    channel: 'Lime Tube[라임튜브]',
    timeAgo: '7년 전',
    views: '조회수 3,707,249회',
    viewsNum: 3707249,
    videoUrl: 'https://www.youtube.com/watch?v=3W9KANpIEzE',
    thumb: 'https://i.ytimg.com/vi/3W9KANpIEzE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBbm98LC-IM5zG0DbXyUg0aSIMhMg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 27,
    id: 'HJeL1WZqnhA',
    type: 'shorts',
    title: '#shorts 아이디어 없는 개그맨들이 선택한 몸개그?! 김경진 , 오정태 콤비의 화제의영상~ 화를 풀어 드립니다!!',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 794회',
    viewsNum: 794,
    videoUrl: 'https://www.youtube.com/shorts/HJeL1WZqnhA',
    thumb: 'https://i.ytimg.com/vi/HJeL1WZqnhA/frame0.jpg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 28,
    id: '33hV-X0DmwI',
    type: 'video',
    title: '더 일찍 알았더라면 좋았을 천재적인 학교 생활 꿀팁',
    channel: '5 분 Tricks',
    timeAgo: '3년 전',
    views: '조회수 3,404,133회',
    viewsNum: 3404133,
    videoUrl: 'https://www.youtube.com/watch?v=33hV-X0DmwI',
    thumb: 'https://i.ytimg.com/vi/33hV-X0DmwI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDrMkTi93tx-ojzVH0GErbjMzKoAQ',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 29,
    id: 'yCTUtdAqNFU',
    type: 'shorts',
    title: '[실시간]야외방송 결과는?!#천안 #버스 #텐션 #트로트 #음방 #라이브 #shorts',
    channel: '차니와띠아',
    timeAgo: '최근',
    views: '75명 시청 중',
    viewsNum: 75,
    videoUrl: 'https://www.youtube.com/shorts/yCTUtdAqNFU',
    thumb: 'https://i.ytimg.com/vi/yCTUtdAqNFU/hqdefault.jpg?v=6aa88aeb&sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCM2ta2-IyNgPyx79wVvF_h00LEFA',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 30,
    id: 'gKktfq7v03o',
    type: 'video',
    title: '아파트~아파트~♬ 영끌해서 샀는데..미래엔 재건축 어렵다고?! | SBS 뉴스토리',
    channel: 'SBS 뉴스',
    timeAgo: '스트리밍 시간: 1년 전',
    views: '조회수 3,385,973회',
    viewsNum: 3385973,
    videoUrl: 'https://www.youtube.com/watch?v=gKktfq7v03o',
    thumb: 'https://i.ytimg.com/vi/gKktfq7v03o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBpz0S86d3xq9oeQUenYp6qkuA_Vg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 31,
    id: '42jPXgkqfwk',
    type: 'shorts',
    title: '직장인 연차 꿀팁ㅋㅋㅋㅋㅋ #shorts',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/42jPXgkqfwk',
    thumb: 'https://i.ytimg.com/vi/42jPXgkqfwk/frame0.jpg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 32,
    id: 'uRMzYr6Z7ps',
    type: 'video',
    title: '#(인기급상승동영상) 올해는 매실청 이제 가족 에게 독약 그만 먹이시고 이렇게 하세요 #1인식사',
    channel: '주부나라',
    timeAgo: '4년 전',
    views: '조회수 3,225,683회',
    viewsNum: 3225683,
    videoUrl: 'https://www.youtube.com/watch?v=uRMzYr6Z7ps',
    thumb: 'https://i.ytimg.com/vi/uRMzYr6Z7ps/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC6L8alZPJbCBz4j8_LLpYevakH2Q',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 33,
    id: 'gflMTBswoNg',
    type: 'shorts',
    title: '대부분 모르는 인천공항 숨겨진 개꿀 장소🍯',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/gflMTBswoNg',
    thumb: 'https://i.ytimg.com/vi/gflMTBswoNg/frame0.jpg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 34,
    id: 'p4QOyuD3NRo',
    type: 'video',
    title: '엄마의 생활 꿀팁',
    channel: '소맥거핀',
    timeAgo: '3년 전',
    views: '조회수 3,097,167회',
    viewsNum: 3097167,
    videoUrl: 'https://www.youtube.com/watch?v=p4QOyuD3NRo',
    thumb: 'https://i.ytimg.com/vi/p4QOyuD3NRo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvzsBFQzS8Ooxh5Wh1VkzmpopGNg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 35,
    id: 'Dc3_H8IgVSA',
    type: 'shorts',
    title: '이 작은 꿀팁 하나로 반죽기가 완벽해졌다! #shorts',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/Dc3_H8IgVSA',
    thumb: 'https://i.ytimg.com/vi/Dc3_H8IgVSA/frame0.jpg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 36,
    id: 'SBLlWU2q1ms',
    type: 'video',
    title: '#(인기급상승동영상) 페트병으로 지긋지긋한 벌레들 모두 없애는 방법',
    channel: '주부나라',
    timeAgo: '4년 전',
    views: '조회수 3,009,192회',
    viewsNum: 3009192,
    videoUrl: 'https://www.youtube.com/watch?v=SBLlWU2q1ms',
    thumb: 'https://i.ytimg.com/vi/SBLlWU2q1ms/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD55xreF07r3_PD7bmcQv5UyfA4tA',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 37,
    id: 'VzTBt42xcZQ',
    type: 'shorts',
    title: '나만 몰랐던 인생 꿀팁',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/VzTBt42xcZQ',
    thumb: 'https://i.ytimg.com/vi/VzTBt42xcZQ/frame0.jpg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 38,
    id: 'm5eRDkviKuY',
    type: 'video',
    title: '버리기 아까운 살림은 재활용 해요. 똑똑한 생활 꿀팁을 알려줄 50대 주부  | 전국살림자랑 ep.4',
    channel: '정리마켓',
    timeAgo: '3년 전',
    views: '조회수 2,922,047회',
    viewsNum: 2922047,
    videoUrl: 'https://www.youtube.com/watch?v=m5eRDkviKuY',
    thumb: 'https://i.ytimg.com/vi/m5eRDkviKuY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCTLoK1986CBsmWcFlPeuNceqBUqA',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 39,
    id: 'CbXKXT_ziSk',
    type: 'shorts',
    title: '무거운 짐, 이 매듭 하나면 쉽게 들어 올립니다! #매듭법 #생활꿀팁 #캠핑매듭 #밧줄묶는법 #shorts',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/CbXKXT_ziSk',
    thumb: 'https://i.ytimg.com/vi/CbXKXT_ziSk/frame0.jpg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 40,
    id: '7AkhC_BFKCU',
    type: 'video',
    title: '#(인기급상승동영상)콩나물 매번 삶고 무치지 마세요 콩나물 김치 담아서 냉장고 두고 두고 시원하게 드세요 #1인식사',
    channel: '주부나라',
    timeAgo: '4년 전',
    views: '조회수 2,833,267회',
    viewsNum: 2833267,
    videoUrl: 'https://www.youtube.com/watch?v=7AkhC_BFKCU',
    thumb: 'https://i.ytimg.com/vi/7AkhC_BFKCU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBVBuKyzfmru6ruS25ZTjxhiIM11Q',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 41,
    id: 'S_ZJlTJ42XQ',
    type: 'shorts',
    title: '변기 막혔을때 10초만에 뚫는 꿀팁!!!',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/S_ZJlTJ42XQ',
    thumb: 'https://i.ytimg.com/vi/S_ZJlTJ42XQ/frame0.jpg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 42,
    id: 'XzKPenkVBeE',
    type: 'video',
    title: '\'잠이 보약\' 매일 푹 잤는데?…새로운 연구 결과 나왔다 / SBS / 뉴스딱',
    channel: 'SBS 뉴스',
    timeAgo: '1년 전',
    views: '조회수 2,779,890회',
    viewsNum: 2779890,
    videoUrl: 'https://www.youtube.com/watch?v=XzKPenkVBeE',
    thumb: 'https://i.ytimg.com/vi/XzKPenkVBeE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDF5UjB98SAMHATAvjwBW2jmnzkvw',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 43,
    id: '0yV7Klia6BA',
    type: 'shorts',
    title: '알아두면 평생 써먹는 생활 꿀팁 10가지 #shorts #살림팁 #꿀팁 #생활꿀팁',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/0yV7Klia6BA',
    thumb: 'https://i.ytimg.com/vi/0yV7Klia6BA/frame0.jpg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 44,
    id: 'cbkbtbD8PvE',
    type: 'video',
    title: '와! 이런방법이! 생활이 편리해지는 생활꿀팁/아이디어',
    channel: '태양우주맘',
    timeAgo: '4년 전',
    views: '조회수 2,477,249회',
    viewsNum: 2477249,
    videoUrl: 'https://www.youtube.com/watch?v=cbkbtbD8PvE',
    thumb: 'https://i.ytimg.com/vi/cbkbtbD8PvE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB2thhNuDEuJQD3x2SRcqiSz92Yjw',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 45,
    id: 'exrkmziWQWA',
    type: 'shorts',
    title: '알아두면 평생 써먹는 생활 꿀팁 10가지 #shorts #살림팁 #꿀팁 #생활꿀팁',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/exrkmziWQWA',
    thumb: 'https://i.ytimg.com/vi/exrkmziWQWA/frame0.jpg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 46,
    id: '80EYwpdvMac',
    type: 'video',
    title: '[레전드] 웃고 삽시다! 듣고 있으면 웃음 + 감동이 있는 강연 | #재미있는 #세바시 #배움은 #덤',
    channel: '세바시 강연 Sebasi Talk',
    timeAgo: '1년 전',
    views: '조회수 2,207,409회',
    viewsNum: 2207409,
    videoUrl: 'https://www.youtube.com/watch?v=80EYwpdvMac',
    thumb: 'https://i.ytimg.com/vi/80EYwpdvMac/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBObDTjQF7wDNztWQWp1Mpm5hdoOA',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 47,
    id: '0N577vmdx2Q',
    type: 'shorts',
    title: '알아두면 평생 써먹는 생활 꿀팁 10가지 #shorts #살림팁 #꿀팁 #생활꿀팁',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/0N577vmdx2Q',
    thumb: 'https://i.ytimg.com/vi/0N577vmdx2Q/frame0.jpg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 48,
    id: 'bFzO509IPko',
    type: 'video',
    title: '[오늘 이슈] RM의 ‘갓’ 인터뷰 “식민지였던 한국이 성공한 이유” / KBS 2023.03.14.',
    channel: 'KBS News',
    timeAgo: '3년 전',
    views: '조회수 2,015,331회',
    viewsNum: 2015331,
    videoUrl: 'https://www.youtube.com/watch?v=bFzO509IPko',
    thumb: 'https://i.ytimg.com/vi/bFzO509IPko/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATigFHsCH7nNjzSGGQvi1KCUSOlQ',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 49,
    id: 'QeDv4VsImP0',
    type: 'shorts',
    title: '알아두면 평생 써먹는 생활 꿀팁 10가지 #shorts #살림팁 #꿀팁 #생활꿀팁',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/QeDv4VsImP0',
    thumb: 'https://i.ytimg.com/vi/QeDv4VsImP0/frame0.jpg',
    tags: ['전체'],
    period: 'today'
  },
  {
    rank: 50,
    id: '3RbRyHcyI2s',
    type: 'video',
    title: '1탄-7탄 생활꿀팁 모음📚한번 알면 평생 편한 소소한 꿀팁 36가지!!',
    channel: 'YummyAt12시에맛나요',
    timeAgo: '5년 전',
    views: '조회수 1,981,382회',
    viewsNum: 1981382,
    videoUrl: 'https://www.youtube.com/watch?v=3RbRyHcyI2s',
    thumb: 'https://i.ytimg.com/vi/3RbRyHcyI2s/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBojZ2J9klgaiGxexXcbiA3t2K8WA',
    tags: ['전체'],
    period: 'today'
  }
];

// 2. [최근 일주일 (7일)] 실시간 인기 & 화제 영상 50개
window.VIRAL_SHORTS_WEEK = [
  {
    rank: 1,
    id: 'nE90yob-xB4',
    type: 'shorts',
    title: '2.6m파도가 아니라 쓰나미야',
    channel: '메론나무',
    timeAgo: '15년 전',
    views: '조회수 10,467,326회',
    viewsNum: 10467326,
    videoUrl: 'https://www.youtube.com/shorts/nE90yob-xB4',
    thumb: 'https://i.ytimg.com/vi/nE90yob-xB4/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARgjIGAofzAP&rs=AOn4CLBAcxadzZkPLYwkcWUMz7mZvSiGbQ',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 2,
    id: '5faE7RCCF9U',
    type: 'video',
    title: '와 뜨거워',
    channel: '숏박스',
    timeAgo: '1년 전',
    views: '조회수 15,056,587회',
    viewsNum: 15056587,
    videoUrl: 'https://www.youtube.com/watch?v=5faE7RCCF9U',
    thumb: 'https://i.ytimg.com/vi/5faE7RCCF9U/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvzf0uyCq6TxtCXmiJQiSvUOp9YA',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 3,
    id: 'w_7UWSjdvIs',
    type: 'shorts',
    title: 'LIVE WWE 2K25 Gameplay #shorts #shortsfeed',
    channel: 'Urms gaming',
    timeAgo: '스트리밍 시간: 12시간 전',
    views: '조회수 271,099회',
    viewsNum: 271099,
    videoUrl: 'https://www.youtube.com/shorts/w_7UWSjdvIs',
    thumb: 'https://i.ytimg.com/vi/w_7UWSjdvIs/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBKfGWe6xJmXIN_DNgzL4eLmLIH7g',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 4,
    id: 'gPN0pYVZFW0',
    type: 'video',
    title: '2026년 9월 15일 알고리즘에 뜰 영상',
    channel: '스토리',
    timeAgo: '5년 전',
    views: '조회수 14,802,054회',
    viewsNum: 14802054,
    videoUrl: 'https://www.youtube.com/watch?v=gPN0pYVZFW0',
    thumb: 'https://i.ytimg.com/vi/gPN0pYVZFW0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAsSJBQKDfLf8hYdfXEamp97pREog',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 5,
    id: 'f2dMX32KT9s',
    type: 'shorts',
    title: '[실시간]일요일아침 결혼식장가기전 라이브#천안 #버스 #텐션 #트로트 #음방 #라이브 #shorts',
    channel: '차니와띠아',
    timeAgo: '스트리밍 시간: 1일 전',
    views: '조회수 194,966회',
    viewsNum: 194966,
    videoUrl: 'https://www.youtube.com/shorts/f2dMX32KT9s',
    thumb: 'https://i.ytimg.com/vi/f2dMX32KT9s/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCJyq4yy58LG8bTO-SaHYi_Cz9lLg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 6,
    id: 'R9O30wgdmw8',
    type: 'video',
    title: '[BBS 인기동영상] 독경_천수경 (영인스님) #BBS염불독경',
    channel: 'BBS 불교방송',
    timeAgo: '5년 전',
    views: '조회수 11,820,809회',
    viewsNum: 11820809,
    videoUrl: 'https://www.youtube.com/watch?v=R9O30wgdmw8',
    thumb: 'https://i.ytimg.com/vi/R9O30wgdmw8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCuLldNxH4I7Gouz5DYX5f0yWk7gA',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 7,
    id: 'hrB3F-4To94',
    type: 'shorts',
    title: '[실시간]주말버스똥꼬쇼 #천안 #버스 #텐션 #트로트 #음방 #라이브 #shorts',
    channel: '차니와띠아',
    timeAgo: '스트리밍 시간: 3일 전',
    views: '조회수 133,480회',
    viewsNum: 133480,
    videoUrl: 'https://www.youtube.com/shorts/hrB3F-4To94',
    thumb: 'https://i.ytimg.com/vi/hrB3F-4To94/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCjOT629DaRwbAZbYwllidNFLaeVw',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 8,
    id: 'VuDY1PBAuWU',
    type: 'video',
    title: '한국인이라면 다 봤을 법한 유튜브 TOP 50 웃긴 동영상 댓글 모음 2탄',
    channel: '유튜브레전드',
    timeAgo: '4년 전',
    views: '조회수 10,706,890회',
    viewsNum: 10706890,
    videoUrl: 'https://www.youtube.com/watch?v=VuDY1PBAuWU',
    thumb: 'https://i.ytimg.com/vi/VuDY1PBAuWU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCKwyYpDE3pcieHaPl8cTLEWX1WbQ',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 9,
    id: 'OtbF88cGJKo',
    type: 'shorts',
    title: '[실시간]주말버스똥꼬쇼(2부)#천안 #버스 #텐션 #트로트 #음방 #라이브 #shorts',
    channel: '차니와띠아',
    timeAgo: '스트리밍 시간: 2일 전',
    views: '조회수 120,381회',
    viewsNum: 120381,
    videoUrl: 'https://www.youtube.com/shorts/OtbF88cGJKo',
    thumb: 'https://i.ytimg.com/vi/OtbF88cGJKo/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA5pCNzmSNOzqJR-hLENN8uz19hEA',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 10,
    id: 'bTizqvC5X9o',
    type: 'video',
    title: '[BBS 인기동영상] 독경_반야심경 (영인스님) #매일듣는독경',
    channel: 'BBS 불교방송',
    timeAgo: '7년 전',
    views: '조회수 9,196,183회',
    viewsNum: 9196183,
    videoUrl: 'https://www.youtube.com/watch?v=bTizqvC5X9o',
    thumb: 'https://i.ytimg.com/vi/bTizqvC5X9o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCrIH-eap_vucJ0JfTQaxmawduuWA',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 11,
    id: 'zcHvH_Unojs',
    type: 'shorts',
    title: '[실시간]버스똥꼬쇼(2부)!#천안 #버스 #텐션 #트로트 #음방 #라이브 #shorts',
    channel: '차니와띠아',
    timeAgo: '스트리밍 시간: 16시간 전',
    views: '조회수 90,789회',
    viewsNum: 90789,
    videoUrl: 'https://www.youtube.com/shorts/zcHvH_Unojs',
    thumb: 'https://i.ytimg.com/vi/zcHvH_Unojs/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCGBA9J7Ln25vMPk0pXaNJA3feYsg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 12,
    id: 'ge0bwN5U2-o',
    type: 'video',
    title: '[BBS 인기동영상] 독경_금강경 독송  (영인스님)  한글/한문 자막 #매일기도 #BBS염불독경',
    channel: 'BBS 불교방송',
    timeAgo: '5년 전',
    views: '조회수 8,357,015회',
    viewsNum: 8357015,
    videoUrl: 'https://www.youtube.com/watch?v=ge0bwN5U2-o',
    thumb: 'https://i.ytimg.com/vi/ge0bwN5U2-o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCB-1oEj-BZbKN4tmDEKZMFKYZwOQ',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 13,
    id: 'Tz14FFObpH8',
    type: 'shorts',
    title: '오싹오싹 니니모가 어떻게 변할까? 😈 #shorts',
    channel: '호기! 핑크퐁 - 놀면서 배워요',
    timeAgo: '1일 전',
    views: '조회수 68,624회',
    viewsNum: 68624,
    videoUrl: 'https://www.youtube.com/shorts/Tz14FFObpH8',
    thumb: 'https://i.ytimg.com/vi/Tz14FFObpH8/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARhJIDgofzAP&rs=AOn4CLCEFcaG26Y35dhz81ilnE1vWe9vyQ',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 14,
    id: 'rOydU8F_lio',
    type: 'video',
    title: '"침실에서 당장 버려야"...3가지 지목한 의사의 경고 [지금이뉴스] / YTN',
    channel: 'YTN',
    timeAgo: '1년 전',
    views: '조회수 7,231,343회',
    viewsNum: 7231343,
    videoUrl: 'https://www.youtube.com/watch?v=rOydU8F_lio',
    thumb: 'https://i.ytimg.com/vi/rOydU8F_lio/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCxdt5z-loWeWDV1PqEQGlA52AjhQ',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 15,
    id: 'HtuiNaPgChE',
    type: 'shorts',
    title: 'BTS (KOREA) 🇰🇷 vs Harry Styles (UK) 🇬🇧 - Trending Top Globally!! #shorts',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 898회',
    viewsNum: 898,
    videoUrl: 'https://www.youtube.com/shorts/HtuiNaPgChE',
    thumb: 'https://i.ytimg.com/vi/HtuiNaPgChE/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 16,
    id: 'pFxM98oPGDc',
    type: 'video',
    title: '[BBS 인기동영상] 독경_금강경 독송 (상진스님)  #매일기도 #BBS염불독경',
    channel: 'BBS 불교방송',
    timeAgo: '7년 전',
    views: '조회수 6,861,503회',
    viewsNum: 6861503,
    videoUrl: 'https://www.youtube.com/watch?v=pFxM98oPGDc',
    thumb: 'https://i.ytimg.com/vi/pFxM98oPGDc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCxMGk-7-C6gC3BvQrjavoPj8C_AQ',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 17,
    id: 'ndBa2JbXpAA',
    type: 'shorts',
    title: '이케아 직원들도 몰래 사 간다는 레전드 도마 😱 #공간활용 #꿀팁 #살림꿀팁 #이케아 #좁은집인테리어  #쇼츠 #살림초보',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 835회',
    viewsNum: 835,
    videoUrl: 'https://www.youtube.com/shorts/ndBa2JbXpAA',
    thumb: 'https://i.ytimg.com/vi/ndBa2JbXpAA/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 18,
    id: 'cItcwI3yd4M',
    type: 'video',
    title: '[BBS 인기동영상] 법륜스님_"행복의 길을 찾아서, 괴로움과 즐거움의 반복인 우리 삶을 어떻게 행복하게 살 것인가" #법륜스님토크콘서트 #행복의길',
    channel: 'BBS 불교방송',
    timeAgo: '6년 전',
    views: '조회수 4,852,694회',
    viewsNum: 4852694,
    videoUrl: 'https://www.youtube.com/watch?v=cItcwI3yd4M',
    thumb: 'https://i.ytimg.com/vi/cItcwI3yd4M/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDgbDaO_iUBgjjvcQAZCba7MogI1A',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 19,
    id: 'VqAMet_qgxQ',
    type: 'shorts',
    title: 'AI 맞춤형 제품 인기 #shorts',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 502회',
    viewsNum: 502,
    videoUrl: 'https://www.youtube.com/shorts/VqAMet_qgxQ',
    thumb: 'https://i.ytimg.com/vi/VqAMet_qgxQ/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 20,
    id: 'NeNJ7wF8wHg',
    type: 'video',
    title: 'Best video compilation 인기 동영상 모음집 [K-POP COVER DANCE]',
    channel: '퇴경아 약먹자',
    timeAgo: '10년 전',
    views: '조회수 4,511,789회',
    viewsNum: 4511789,
    videoUrl: 'https://www.youtube.com/watch?v=NeNJ7wF8wHg',
    thumb: 'https://i.ytimg.com/vi/NeNJ7wF8wHg/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARh_IDYoLzAP&rs=AOn4CLDQl7alDhIRQXr4kX_593Za3h1zsQ',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 21,
    id: '42jPXgkqfwk',
    type: 'shorts',
    title: '직장인 연차 꿀팁ㅋㅋㅋㅋㅋ #shorts',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/42jPXgkqfwk',
    thumb: 'https://i.ytimg.com/vi/42jPXgkqfwk/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 22,
    id: '2ku8q4ZYtOg',
    type: 'video',
    title: '\'조회수 1억\' 찍은 6초 영상…"얼마라고?" 대박 터졌다 (자막뉴스) / SBS',
    channel: 'SBS 뉴스',
    timeAgo: '1년 전',
    views: '조회수 4,407,131회',
    viewsNum: 4407131,
    videoUrl: 'https://www.youtube.com/watch?v=2ku8q4ZYtOg',
    thumb: 'https://i.ytimg.com/vi/2ku8q4ZYtOg/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC-uELr1L2UEimV8gA0d5txKaSQBQ',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 23,
    id: 'lDw6-kbColA',
    type: 'shorts',
    title: '평생 써먹는 세제 리필 활용법',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/lDw6-kbColA',
    thumb: 'https://i.ytimg.com/vi/lDw6-kbColA/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 24,
    id: '33hV-X0DmwI',
    type: 'video',
    title: '더 일찍 알았더라면 좋았을 천재적인 학교 생활 꿀팁',
    channel: '5 분 Tricks',
    timeAgo: '3년 전',
    views: '조회수 3,404,152회',
    viewsNum: 3404152,
    videoUrl: 'https://www.youtube.com/watch?v=33hV-X0DmwI',
    thumb: 'https://i.ytimg.com/vi/33hV-X0DmwI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDrMkTi93tx-ojzVH0GErbjMzKoAQ',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 25,
    id: 'dgaFRpqjUd4',
    type: 'shorts',
    title: '바지 끈 거슬릴 때 깔끔하게 묶는 꿀팁! 👖',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/dgaFRpqjUd4',
    thumb: 'https://i.ytimg.com/vi/dgaFRpqjUd4/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 26,
    id: 'gKktfq7v03o',
    type: 'video',
    title: '아파트~아파트~♬ 영끌해서 샀는데..미래엔 재건축 어렵다고?! | SBS 뉴스토리',
    channel: 'SBS 뉴스',
    timeAgo: '스트리밍 시간: 1년 전',
    views: '조회수 3,385,973회',
    viewsNum: 3385973,
    videoUrl: 'https://www.youtube.com/watch?v=gKktfq7v03o',
    thumb: 'https://i.ytimg.com/vi/gKktfq7v03o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBpz0S86d3xq9oeQUenYp6qkuA_Vg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 27,
    id: 'gflMTBswoNg',
    type: 'shorts',
    title: '대부분 모르는 인천공항 숨겨진 개꿀 장소🍯',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/gflMTBswoNg',
    thumb: 'https://i.ytimg.com/vi/gflMTBswoNg/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 28,
    id: 'p4QOyuD3NRo',
    type: 'video',
    title: '엄마의 생활 꿀팁',
    channel: '소맥거핀',
    timeAgo: '3년 전',
    views: '조회수 3,097,187회',
    viewsNum: 3097187,
    videoUrl: 'https://www.youtube.com/watch?v=p4QOyuD3NRo',
    thumb: 'https://i.ytimg.com/vi/p4QOyuD3NRo/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvzsBFQzS8Ooxh5Wh1VkzmpopGNg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 29,
    id: '45Yv3shxi_o',
    type: 'shorts',
    title: '고음 안되는 사람들 대부분이 모르는 \'특급 고음 꿀팁\' #shorts',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/45Yv3shxi_o',
    thumb: 'https://i.ytimg.com/vi/45Yv3shxi_o/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 30,
    id: 'm5eRDkviKuY',
    type: 'video',
    title: '버리기 아까운 살림은 재활용 해요. 똑똑한 생활 꿀팁을 알려줄 50대 주부  | 전국살림자랑 ep.4',
    channel: '정리마켓',
    timeAgo: '3년 전',
    views: '조회수 2,922,047회',
    viewsNum: 2922047,
    videoUrl: 'https://www.youtube.com/watch?v=m5eRDkviKuY',
    thumb: 'https://i.ytimg.com/vi/m5eRDkviKuY/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCTLoK1986CBsmWcFlPeuNceqBUqA',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 31,
    id: 'gnEgFbEFW8s',
    type: 'shorts',
    title: '이 매듭 하나면 절대 쉽게 안 풀립니다! 😱',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/gnEgFbEFW8s',
    thumb: 'https://i.ytimg.com/vi/gnEgFbEFW8s/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 32,
    id: 'XzKPenkVBeE',
    type: 'video',
    title: '\'잠이 보약\' 매일 푹 잤는데?…새로운 연구 결과 나왔다 / SBS / 뉴스딱',
    channel: 'SBS 뉴스',
    timeAgo: '1년 전',
    views: '조회수 2,779,890회',
    viewsNum: 2779890,
    videoUrl: 'https://www.youtube.com/watch?v=XzKPenkVBeE',
    thumb: 'https://i.ytimg.com/vi/XzKPenkVBeE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDF5UjB98SAMHATAvjwBW2jmnzkvw',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 33,
    id: 'CbXKXT_ziSk',
    type: 'shorts',
    title: '무거운 짐, 이 매듭 하나면 쉽게 들어 올립니다! #매듭법 #생활꿀팁 #캠핑매듭 #밧줄묶는법 #shorts',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/CbXKXT_ziSk',
    thumb: 'https://i.ytimg.com/vi/CbXKXT_ziSk/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 34,
    id: 'cbkbtbD8PvE',
    type: 'video',
    title: '와! 이런방법이! 생활이 편리해지는 생활꿀팁/아이디어',
    channel: '태양우주맘',
    timeAgo: '4년 전',
    views: '조회수 2,477,249회',
    viewsNum: 2477249,
    videoUrl: 'https://www.youtube.com/watch?v=cbkbtbD8PvE',
    thumb: 'https://i.ytimg.com/vi/cbkbtbD8PvE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB2thhNuDEuJQD3x2SRcqiSz92Yjw',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 35,
    id: 'vWCG0Z1a4Mg',
    type: 'shorts',
    title: '3초 만에 끝내는 봉투 단단하게 묶는 매듭법! 🪢',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/vWCG0Z1a4Mg',
    thumb: 'https://i.ytimg.com/vi/vWCG0Z1a4Mg/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 36,
    id: 'bFzO509IPko',
    type: 'video',
    title: '[오늘 이슈] RM의 ‘갓’ 인터뷰 “식민지였던 한국이 성공한 이유” / KBS 2023.03.14.',
    channel: 'KBS News',
    timeAgo: '3년 전',
    views: '조회수 2,015,340회',
    viewsNum: 2015340,
    videoUrl: 'https://www.youtube.com/watch?v=bFzO509IPko',
    thumb: 'https://i.ytimg.com/vi/bFzO509IPko/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATigFHsCH7nNjzSGGQvi1KCUSOlQ',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 37,
    id: 'p34rhjSKOis',
    type: 'shorts',
    title: '렌치 2개를 밧줄 하나로 묶는 놀라운 방법😳',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/p34rhjSKOis',
    thumb: 'https://i.ytimg.com/vi/p34rhjSKOis/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 38,
    id: '3RbRyHcyI2s',
    type: 'video',
    title: '1탄-7탄 생활꿀팁 모음📚한번 알면 평생 편한 소소한 꿀팁 36가지!!',
    channel: 'YummyAt12시에맛나요',
    timeAgo: '5년 전',
    views: '조회수 1,981,382회',
    viewsNum: 1981382,
    videoUrl: 'https://www.youtube.com/watch?v=3RbRyHcyI2s',
    thumb: 'https://i.ytimg.com/vi/3RbRyHcyI2s/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBojZ2J9klgaiGxexXcbiA3t2K8WA',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 39,
    id: 'MmmYRS43304',
    type: 'shorts',
    title: '99%가 몰랐던 초간단 로프 매듭법 모음 끝판왕  #매듭법 #생활꿀팁 #캠핑매듭 #밧줄묶는법 #shorts',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/MmmYRS43304',
    thumb: 'https://i.ytimg.com/vi/MmmYRS43304/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 40,
    id: 'K3PDRB9R-YI',
    type: 'video',
    title: '- 노부부의 한입만- (컬투쇼 레전드사연 애니메이션) by YOUTOO(유투) (KOR sub)',
    channel: 'YOUTOO - 유투 애니메이션 -',
    timeAgo: '3년 전',
    views: '조회수 1,661,995회',
    viewsNum: 1661995,
    videoUrl: 'https://www.youtube.com/watch?v=K3PDRB9R-YI',
    thumb: 'https://i.ytimg.com/vi/K3PDRB9R-YI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCe2dFAevOysvo2mo1D0-W5eAQkwQ',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 41,
    id: 'S_ZJlTJ42XQ',
    type: 'shorts',
    title: '변기 막혔을때 10초만에 뚫는 꿀팁!!!',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/S_ZJlTJ42XQ',
    thumb: 'https://i.ytimg.com/vi/S_ZJlTJ42XQ/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 42,
    id: 'uYNQVmX3gsM',
    type: 'video',
    title: '[BBS 인기동영상] 법륜스님_법륜스님께서는 왜 출가를 하셨나요 #출가이유 #법륜스님출가',
    channel: 'BBS 불교방송',
    timeAgo: '6년 전',
    views: '조회수 1,633,187회',
    viewsNum: 1633187,
    videoUrl: 'https://www.youtube.com/watch?v=uYNQVmX3gsM',
    thumb: 'https://i.ytimg.com/vi/uYNQVmX3gsM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDrhsNWo2AR_bdaZPQrdkeEzVVanw',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 43,
    id: '0yV7Klia6BA',
    type: 'shorts',
    title: '알아두면 평생 써먹는 생활 꿀팁 10가지 #shorts #살림팁 #꿀팁 #생활꿀팁',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/0yV7Klia6BA',
    thumb: 'https://i.ytimg.com/vi/0yV7Klia6BA/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 44,
    id: 'OoMOqMfGb0g',
    type: 'video',
    title: '[BBS 인기동영상] 띵작 몰아보기_고승열전 경허대선사, 불교가 추구하는 길 없는 길 #고승열전 #경허대선사 #고승열전경허대선사',
    channel: 'BBS 불교방송',
    timeAgo: '4년 전',
    views: '조회수 1,591,089회',
    viewsNum: 1591089,
    videoUrl: 'https://www.youtube.com/watch?v=OoMOqMfGb0g',
    thumb: 'https://i.ytimg.com/vi/OoMOqMfGb0g/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLADc7elLfcaDNJSZ6XDBRRLRgGw2Q',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 45,
    id: 'exrkmziWQWA',
    type: 'shorts',
    title: '알아두면 평생 써먹는 생활 꿀팁 10가지 #shorts #살림팁 #꿀팁 #생활꿀팁',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/exrkmziWQWA',
    thumb: 'https://i.ytimg.com/vi/exrkmziWQWA/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 46,
    id: 'iOJM4GUnE04',
    type: 'video',
    title: '와! 이런방법이! 생활꿀팁  best몰아보기',
    channel: '태양우주맘',
    timeAgo: '4년 전',
    views: '조회수 1,498,075회',
    viewsNum: 1498075,
    videoUrl: 'https://www.youtube.com/watch?v=iOJM4GUnE04',
    thumb: 'https://i.ytimg.com/vi/iOJM4GUnE04/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCaycd9GoPRKTWMhsyA9NzbqJNo0Q',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 47,
    id: '0N577vmdx2Q',
    type: 'shorts',
    title: '알아두면 평생 써먹는 생활 꿀팁 10가지 #shorts #살림팁 #꿀팁 #생활꿀팁',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/0N577vmdx2Q',
    thumb: 'https://i.ytimg.com/vi/0N577vmdx2Q/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 48,
    id: 'rQ6Vh0kzTpg',
    type: 'video',
    title: '⭐️480만 감사 인기동영상 재편집⭐️ 찐 9모양 발톱의 매력에 빠져보아요~  ingrown toenail - Fresh Foot 풋풋한리쌤 성수본점',
    channel: '풋풋한Lee쌤 Fresh Foot',
    timeAgo: '8개월 전',
    views: '조회수 1,345,288회',
    viewsNum: 1345288,
    videoUrl: 'https://www.youtube.com/watch?v=rQ6Vh0kzTpg',
    thumb: 'https://i.ytimg.com/vi/rQ6Vh0kzTpg/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDY_SnAnwdizaBNqY1lPHmLIDPzAg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 49,
    id: 'QeDv4VsImP0',
    type: 'shorts',
    title: '알아두면 평생 써먹는 생활 꿀팁 10가지 #shorts #살림팁 #꿀팁 #생활꿀팁',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 급상승',
    viewsNum: 0,
    videoUrl: 'https://www.youtube.com/shorts/QeDv4VsImP0',
    thumb: 'https://i.ytimg.com/vi/QeDv4VsImP0/frame0.jpg',
    tags: ['전체'],
    period: 'week'
  },
  {
    rank: 50,
    id: 'zlpHHCSu_hA',
    type: 'video',
    title: '살림 고수 1억 2천만명이 확인한 충격적인 생활꿀팁 30가지 몰아보기',
    channel: '살림연구소 오클',
    timeAgo: '1년 전',
    views: '조회수 1,319,949회',
    viewsNum: 1319949,
    videoUrl: 'https://www.youtube.com/watch?v=zlpHHCSu_hA',
    thumb: 'https://i.ytimg.com/vi/zlpHHCSu_hA/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBrVcmuMMr-9j6qePbh-M3Tx8Fp7g',
    tags: ['전체'],
    period: 'week'
  }
];

// 3. [30일 (1개월)] 실시간 인기 & 화제 영상 50개
window.VIRAL_SHORTS_MONTH = [
  {
    rank: 1,
    id: 'gTo-yidtgQo',
    type: 'shorts',
    title: 'BYD \'묵묵부답\' #shorts / YTN',
    channel: 'YTN',
    timeAgo: '3주 전',
    views: '조회수 2,588,732회',
    viewsNum: 2588732,
    videoUrl: 'https://www.youtube.com/shorts/gTo-yidtgQo',
    thumb: 'https://i.ytimg.com/vi/gTo-yidtgQo/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBzgWAAoAKigIMCAAQARgTIEcofzAP&rs=AOn4CLCD_HMDX3ooB_jmkjUAd7wwhWhx0w',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 2,
    id: '5faE7RCCF9U',
    type: 'video',
    title: '와 뜨거워',
    channel: '숏박스',
    timeAgo: '1년 전',
    views: '조회수 15,056,587회',
    viewsNum: 15056587,
    videoUrl: 'https://www.youtube.com/watch?v=5faE7RCCF9U',
    thumb: 'https://i.ytimg.com/vi/5faE7RCCF9U/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDvzf0uyCq6TxtCXmiJQiSvUOp9YA',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 3,
    id: 'oXPjCxUwQM4',
    type: 'shorts',
    title: '목숨 걸고 \'전력질주\' #shorts / YTN',
    channel: 'YTN',
    timeAgo: '2주 전',
    views: '조회수 2,477,312회',
    viewsNum: 2477312,
    videoUrl: 'https://www.youtube.com/shorts/oXPjCxUwQM4',
    thumb: 'https://i.ytimg.com/vi/oXPjCxUwQM4/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBzgWAAoAKigIMCAAQARgYIEsofzAP&rs=AOn4CLAt1k-t4K04R6unogOtGhR7MQAyEg',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 4,
    id: 'gPN0pYVZFW0',
    type: 'video',
    title: '2026년 9월 15일 알고리즘에 뜰 영상',
    channel: '스토리',
    timeAgo: '5년 전',
    views: '조회수 14,802,054회',
    viewsNum: 14802054,
    videoUrl: 'https://www.youtube.com/watch?v=gPN0pYVZFW0',
    thumb: 'https://i.ytimg.com/vi/gPN0pYVZFW0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAsSJBQKDfLf8hYdfXEamp97pREog',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 5,
    id: 'IUR7bE0-vME',
    type: 'shorts',
    title: '홍장원이 끝내 터뜨린 충격 폭로 ㄷㄷ #shorts',
    channel: '시사픽26',
    timeAgo: '3주 전',
    views: '조회수 2,440,606회',
    viewsNum: 2440606,
    videoUrl: 'https://www.youtube.com/shorts/IUR7bE0-vME',
    thumb: 'https://i.ytimg.com/vi/IUR7bE0-vME/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARhUIEkocjAP&rs=AOn4CLDIAzaicGoAZ5t8dVqfat91wBjafQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 6,
    id: 'R9O30wgdmw8',
    type: 'video',
    title: '[BBS 인기동영상] 독경_천수경 (영인스님) #BBS염불독경',
    channel: 'BBS 불교방송',
    timeAgo: '5년 전',
    views: '조회수 11,820,809회',
    viewsNum: 11820809,
    videoUrl: 'https://www.youtube.com/watch?v=R9O30wgdmw8',
    thumb: 'https://i.ytimg.com/vi/R9O30wgdmw8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCuLldNxH4I7Gouz5DYX5f0yWk7gA',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 7,
    id: '8rhAOkJwbco',
    type: 'shorts',
    title: '버스 탄 아이들 창밖 \'초현실\' 대경악.."온다 와! 도망쳐" #Shorts (MBC뉴스)',
    channel: 'MBCNEWS',
    timeAgo: '2주 전',
    views: '조회수 2,308,884회',
    viewsNum: 2308884,
    videoUrl: 'https://www.youtube.com/shorts/8rhAOkJwbco',
    thumb: 'https://i.ytimg.com/vi/8rhAOkJwbco/hq720_2.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARggIDwofzAP&rs=AOn4CLAELTPnEzjBAPK5PCCc7o0LleFSuw',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 8,
    id: 'VuDY1PBAuWU',
    type: 'video',
    title: '한국인이라면 다 봤을 법한 유튜브 TOP 50 웃긴 동영상 댓글 모음 2탄',
    channel: '유튜브레전드',
    timeAgo: '4년 전',
    views: '조회수 10,706,890회',
    viewsNum: 10706890,
    videoUrl: 'https://www.youtube.com/watch?v=VuDY1PBAuWU',
    thumb: 'https://i.ytimg.com/vi/VuDY1PBAuWU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCKwyYpDE3pcieHaPl8cTLEWX1WbQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 9,
    id: 'Pd856O8UdTM',
    type: 'shorts',
    title: '혁오 신곡 뮤직비디오 공개되자 "영상 내리길" #shorts / KBS',
    channel: 'KBS News',
    timeAgo: '3주 전',
    views: '조회수 2,094,291회',
    viewsNum: 2094291,
    videoUrl: 'https://www.youtube.com/shorts/Pd856O8UdTM',
    thumb: 'https://i.ytimg.com/vi/Pd856O8UdTM/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARgfIDcofzAP&rs=AOn4CLDhjBxll0ZyeMJL1hoYeEVzlYj7Ag',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 10,
    id: 'bTizqvC5X9o',
    type: 'video',
    title: '[BBS 인기동영상] 독경_반야심경 (영인스님) #매일듣는독경',
    channel: 'BBS 불교방송',
    timeAgo: '7년 전',
    views: '조회수 9,196,183회',
    viewsNum: 9196183,
    videoUrl: 'https://www.youtube.com/watch?v=bTizqvC5X9o',
    thumb: 'https://i.ytimg.com/vi/bTizqvC5X9o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCrIH-eap_vucJ0JfTQaxmawduuWA',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 11,
    id: 'KhXVR6tKGFg',
    type: 'shorts',
    title: '[#shorts] 서울 한복판에서 건물이 무너졌다 삼풍백화점 붕괴 직후 | KBS방송',
    channel: '옛날티비 : KBS Archive',
    timeAgo: '3주 전',
    views: '조회수 2,023,265회',
    viewsNum: 2023265,
    videoUrl: 'https://www.youtube.com/shorts/KhXVR6tKGFg',
    thumb: 'https://i.ytimg.com/vi/KhXVR6tKGFg/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARhlIE0oQTAP&rs=AOn4CLAncLRpMo9UGjKigjQnpt-fGyl4Kg',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 12,
    id: 'ge0bwN5U2-o',
    type: 'video',
    title: '[BBS 인기동영상] 독경_금강경 독송  (영인스님)  한글/한문 자막 #매일기도 #BBS염불독경',
    channel: 'BBS 불교방송',
    timeAgo: '5년 전',
    views: '조회수 8,357,015회',
    viewsNum: 8357015,
    videoUrl: 'https://www.youtube.com/watch?v=ge0bwN5U2-o',
    thumb: 'https://i.ytimg.com/vi/ge0bwN5U2-o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCB-1oEj-BZbKN4tmDEKZMFKYZwOQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 13,
    id: '-HIZe83GsdU',
    type: 'shorts',
    title: '"시력 잃는다" 충격 #shorts / YTN',
    channel: 'YTN',
    timeAgo: '3주 전',
    views: '조회수 1,996,889회',
    viewsNum: 1996889,
    videoUrl: 'https://www.youtube.com/shorts/-HIZe83GsdU',
    thumb: 'https://i.ytimg.com/vi/-HIZe83GsdU/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARgTIEcofzAP&rs=AOn4CLAD-Me7Eufw1r4qg_cFEkAr9J2xTw',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 14,
    id: 'rOydU8F_lio',
    type: 'video',
    title: '"침실에서 당장 버려야"...3가지 지목한 의사의 경고 [지금이뉴스] / YTN',
    channel: 'YTN',
    timeAgo: '1년 전',
    views: '조회수 7,231,343회',
    viewsNum: 7231343,
    videoUrl: 'https://www.youtube.com/watch?v=rOydU8F_lio',
    thumb: 'https://i.ytimg.com/vi/rOydU8F_lio/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCxdt5z-loWeWDV1PqEQGlA52AjhQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 15,
    id: '7BJE1iPuFsw',
    type: 'shorts',
    title: '이진숙 제명 안 되면 의원 자격정지라도 채널A #shorts #DLAB #ashorts',
    channel: '채널A News',
    timeAgo: '3주 전',
    views: '조회수 1,748,646회',
    viewsNum: 1748646,
    videoUrl: 'https://www.youtube.com/shorts/7BJE1iPuFsw',
    thumb: 'https://i.ytimg.com/vi/7BJE1iPuFsw/hq720_2.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARgYIBQofzAP&rs=AOn4CLAVSQIG2IdLYTk7ciTptZFZbE6H4w',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 16,
    id: 'pFxM98oPGDc',
    type: 'video',
    title: '[BBS 인기동영상] 독경_금강경 독송 (상진스님)  #매일기도 #BBS염불독경',
    channel: 'BBS 불교방송',
    timeAgo: '7년 전',
    views: '조회수 6,861,503회',
    viewsNum: 6861503,
    videoUrl: 'https://www.youtube.com/watch?v=pFxM98oPGDc',
    thumb: 'https://i.ytimg.com/vi/pFxM98oPGDc/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCxMGk-7-C6gC3BvQrjavoPj8C_AQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 17,
    id: 'O_e_5nN2hrw',
    type: 'shorts',
    title: '"중국인이 국민연금?" 논란 터지자.. #shorts',
    channel: 'SBS 뉴스',
    timeAgo: '2주 전',
    views: '조회수 1,738,453회',
    viewsNum: 1738453,
    videoUrl: 'https://www.youtube.com/shorts/O_e_5nN2hrw',
    thumb: 'https://i.ytimg.com/vi/O_e_5nN2hrw/hq720_2.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBzgWAAoAKigIMCAAQARgiIDcofzAP&rs=AOn4CLD6C1yDFONdjJE0Q_apZt5uUpkJlA',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 18,
    id: 'cItcwI3yd4M',
    type: 'video',
    title: '[BBS 인기동영상] 법륜스님_"행복의 길을 찾아서, 괴로움과 즐거움의 반복인 우리 삶을 어떻게 행복하게 살 것인가" #법륜스님토크콘서트 #행복의길',
    channel: 'BBS 불교방송',
    timeAgo: '6년 전',
    views: '조회수 4,852,694회',
    viewsNum: 4852694,
    videoUrl: 'https://www.youtube.com/watch?v=cItcwI3yd4M',
    thumb: 'https://i.ytimg.com/vi/cItcwI3yd4M/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDgbDaO_iUBgjjvcQAZCba7MogI1A',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 19,
    id: 'DLjLiP3jBvU',
    type: 'shorts',
    title: '\'풍어\' 잡은 참치 버리던 日.. 갑자기 "초밥 대할인"? #Shorts (MBC뉴스)',
    channel: 'MBCNEWS',
    timeAgo: '3주 전',
    views: '조회수 1,697,401회',
    viewsNum: 1697401,
    videoUrl: 'https://www.youtube.com/shorts/DLjLiP3jBvU',
    thumb: 'https://i.ytimg.com/vi/DLjLiP3jBvU/hq720_2.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARggIDwofzAP&rs=AOn4CLC-kq0SEnkDcCd-kyqxAhEHf-JIyQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 20,
    id: 'NeNJ7wF8wHg',
    type: 'video',
    title: 'Best video compilation 인기 동영상 모음집 [K-POP COVER DANCE]',
    channel: '퇴경아 약먹자',
    timeAgo: '10년 전',
    views: '조회수 4,511,789회',
    viewsNum: 4511789,
    videoUrl: 'https://www.youtube.com/watch?v=NeNJ7wF8wHg',
    thumb: 'https://i.ytimg.com/vi/NeNJ7wF8wHg/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARh_IDYoLzAP&rs=AOn4CLDQl7alDhIRQXr4kX_593Za3h1zsQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 21,
    id: 'QBarTdMqYxg',
    type: 'shorts',
    title: '싸이 \'흠뻑쇼\' 추락사고…취재가 시작되자 #shorts / KBS',
    channel: 'KBS News',
    timeAgo: '3주 전',
    views: '조회수 1,495,522회',
    viewsNum: 1495522,
    videoUrl: 'https://www.youtube.com/shorts/QBarTdMqYxg',
    thumb: 'https://i.ytimg.com/vi/QBarTdMqYxg/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARgfIDgofzAP&rs=AOn4CLBQCNTF--e5PkLkScnm0Uq_Tx-YvQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 22,
    id: '2ku8q4ZYtOg',
    type: 'video',
    title: '\'조회수 1억\' 찍은 6초 영상…"얼마라고?" 대박 터졌다 (자막뉴스) / SBS',
    channel: 'SBS 뉴스',
    timeAgo: '1년 전',
    views: '조회수 4,406,820회',
    viewsNum: 4406820,
    videoUrl: 'https://www.youtube.com/watch?v=2ku8q4ZYtOg',
    thumb: 'https://i.ytimg.com/vi/2ku8q4ZYtOg/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC-uELr1L2UEimV8gA0d5txKaSQBQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 23,
    id: 'QOyt7jpUrAI',
    type: 'shorts',
    title: '"사관학교 출신답게" 국방부 정책실장 발언에 고성 /  #채널A #shorts #30짤',
    channel: '채널A News',
    timeAgo: '2주 전',
    views: '조회수 1,438,481회',
    viewsNum: 1438481,
    videoUrl: 'https://www.youtube.com/shorts/QOyt7jpUrAI',
    thumb: 'https://i.ytimg.com/vi/QOyt7jpUrAI/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARhGIEwoZTAP&rs=AOn4CLB5YqEA8MZvbMLOdkdsUv7hMyL_jg',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 24,
    id: '--m5TieGS6Y',
    type: 'video',
    title: '(#인기급상승동영상)밥통에 사과를 넣었더니 그립던 옛맛에 눈물이 납니다',
    channel: '주부나라',
    timeAgo: '3년 전',
    views: '조회수 4,220,507회',
    viewsNum: 4220507,
    videoUrl: 'https://www.youtube.com/watch?v=--m5TieGS6Y',
    thumb: 'https://i.ytimg.com/vi/--m5TieGS6Y/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCBJ5z2GnCL2llMfWE2ZGn7sa7gWA',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 25,
    id: 'kF8yVR3xd2k',
    type: 'shorts',
    title: '건물마저 힘없이 \'와르르\' #shorts / YTN',
    channel: 'YTN',
    timeAgo: '2주 전',
    views: '조회수 1,407,252회',
    viewsNum: 1407252,
    videoUrl: 'https://www.youtube.com/shorts/kF8yVR3xd2k',
    thumb: 'https://i.ytimg.com/vi/kF8yVR3xd2k/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBzgWAAoAKigIMCAAQARgYIEsofzAP&rs=AOn4CLA9e61_h2bCYDZk7yNY6GYxRB50JA',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 26,
    id: '3W9KANpIEzE',
    type: 'video',
    title: '[60분]라임의 인기 동영상 영상모음 미니특공대 파자마삼총사와 소피루비방 indoor playground fun for kids | johny johny',
    channel: 'Lime Tube[라임튜브]',
    timeAgo: '7년 전',
    views: '조회수 3,707,249회',
    viewsNum: 3707249,
    videoUrl: 'https://www.youtube.com/watch?v=3W9KANpIEzE',
    thumb: 'https://i.ytimg.com/vi/3W9KANpIEzE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBbm98LC-IM5zG0DbXyUg0aSIMhMg',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 27,
    id: 'gXBM_zvYsHk',
    type: 'shorts',
    title: '성폭행당하는 딸들…옆에서 \'틱톡\' 본 미국 엄마 #JTBC #Shorts',
    channel: 'JTBC News',
    timeAgo: '3주 전',
    views: '조회수 1,343,429회',
    viewsNum: 1343429,
    videoUrl: 'https://www.youtube.com/shorts/gXBM_zvYsHk',
    thumb: 'https://i.ytimg.com/vi/gXBM_zvYsHk/hq720_2.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARgTIFwofzAP&rs=AOn4CLCnokq3H0fi5YeHuLCWoQPTpcO0dQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 28,
    id: '33hV-X0DmwI',
    type: 'video',
    title: '더 일찍 알았더라면 좋았을 천재적인 학교 생활 꿀팁',
    channel: '5 분 Tricks',
    timeAgo: '3년 전',
    views: '조회수 3,404,133회',
    viewsNum: 3404133,
    videoUrl: 'https://www.youtube.com/watch?v=33hV-X0DmwI',
    thumb: 'https://i.ytimg.com/vi/33hV-X0DmwI/hq720.jpg?sqp=-oaymwEgCNAFEJQDSFXyq4qpAxIIARUAAIhCGAFwAcABBrgC8xg=&rs=AOn4CLD4XmUX1WawRaXgl83yMQIzjU5D5g',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 29,
    id: 'Fpy8wmN6iXM',
    type: 'shorts',
    title: '아수라장 된 거제 #shorts / YTN',
    channel: 'YTN',
    timeAgo: '4주 전',
    views: '조회수 1,300,063회',
    viewsNum: 1300063,
    videoUrl: 'https://www.youtube.com/shorts/Fpy8wmN6iXM',
    thumb: 'https://i.ytimg.com/vi/Fpy8wmN6iXM/hq720_2.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARgYIEoofzAP&rs=AOn4CLBYpldxzIxzniPNQsnqo5GCktSaWQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 30,
    id: 'gKktfq7v03o',
    type: 'video',
    title: '아파트~아파트~♬ 영끌해서 샀는데..미래엔 재건축 어렵다고?! | SBS 뉴스토리',
    channel: 'SBS 뉴스',
    timeAgo: '스트리밍 시간: 1년 전',
    views: '조회수 3,385,973회',
    viewsNum: 3385973,
    videoUrl: 'https://www.youtube.com/watch?v=gKktfq7v03o',
    thumb: 'https://i.ytimg.com/vi/gKktfq7v03o/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBpz0S86d3xq9oeQUenYp6qkuA_Vg',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 31,
    id: 'DYvS52pUnQc',
    type: 'shorts',
    title: '트럼프가 쏘아올린 큰 공 #shorts / YTN',
    channel: 'YTN',
    timeAgo: '3주 전',
    views: '조회수 1,264,843회',
    viewsNum: 1264843,
    videoUrl: 'https://www.youtube.com/shorts/DYvS52pUnQc',
    thumb: 'https://i.ytimg.com/vi/DYvS52pUnQc/hq720_2.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARgXIEoofzAP&rs=AOn4CLCE3X3O8P2kdK04FFy44jhAZTYWOw',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 32,
    id: 'uRMzYr6Z7ps',
    type: 'video',
    title: '#(인기급상승동영상) 올해는 매실청 이제 가족 에게 독약 그만 먹이시고 이렇게 하세요 #1인식사',
    channel: '주부나라',
    timeAgo: '4년 전',
    views: '조회수 3,225,683회',
    viewsNum: 3225683,
    videoUrl: 'https://www.youtube.com/watch?v=uRMzYr6Z7ps',
    thumb: 'https://i.ytimg.com/vi/uRMzYr6Z7ps/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC6L8alZPJbCBz4j8_LLpYevakH2Q',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 33,
    id: '3u7TZkxRJJk',
    type: 'shorts',
    title: '네팔 홍수로 대규모 피해..한국인 8명 연락 두절 #shorts',
    channel: 'SBS 뉴스',
    timeAgo: '2주 전',
    views: '조회수 1,108,827회',
    viewsNum: 1108827,
    videoUrl: 'https://www.youtube.com/shorts/3u7TZkxRJJk',
    thumb: 'https://i.ytimg.com/vi/3u7TZkxRJJk/hq720_2.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARgiIDcofzAP&rs=AOn4CLBYs9NSo13phVVEfg6TxrJ2siRsaw',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 34,
    id: 'p4QOyuD3NRo',
    type: 'video',
    title: '엄마의 생활 꿀팁',
    channel: '소맥거핀',
    timeAgo: '3년 전',
    views: '조회수 3,097,167회',
    viewsNum: 3097167,
    videoUrl: 'https://www.youtube.com/watch?v=p4QOyuD3NRo',
    thumb: 'https://i.ytimg.com/vi/p4QOyuD3NRo/hq720.jpg?sqp=-oaymwEgCNAFEJQDSFXyq4qpAxIIARUAAIhCGAFwAcABBrgC8xg=&rs=AOn4CLAUyV2wQhToagx7eQ89Hh8Zu0gm0w',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 35,
    id: '0vJkgCUHJB8',
    type: 'shorts',
    title: '"장미란씨 혼자 불가능" #shorts / YTN',
    channel: 'YTN',
    timeAgo: '2주 전',
    views: '조회수 1,073,822회',
    viewsNum: 1073822,
    videoUrl: 'https://www.youtube.com/shorts/0vJkgCUHJB8',
    thumb: 'https://i.ytimg.com/vi/0vJkgCUHJB8/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARgXIEkofzAP&rs=AOn4CLCnLvh-Ohhbv9wwtvn97QX3CrcHZA',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 36,
    id: 'SBLlWU2q1ms',
    type: 'video',
    title: '#(인기급상승동영상) 페트병으로 지긋지긋한 벌레들 모두 없애는 방법',
    channel: '주부나라',
    timeAgo: '4년 전',
    views: '조회수 3,009,192회',
    viewsNum: 3009192,
    videoUrl: 'https://www.youtube.com/watch?v=SBLlWU2q1ms',
    thumb: 'https://i.ytimg.com/vi/SBLlWU2q1ms/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD55xreF07r3_PD7bmcQv5UyfA4tA',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 37,
    id: 'H8r6CcJl_wA',
    type: 'shorts',
    title: '"나가서 하세요 개인방송은!"..딱 걸린 \'라이브\' 소동 #Shorts (MBC뉴스)',
    channel: 'MBCNEWS',
    timeAgo: '3주 전',
    views: '조회수 1,045,301회',
    viewsNum: 1045301,
    videoUrl: 'https://www.youtube.com/shorts/H8r6CcJl_wA',
    thumb: 'https://i.ytimg.com/vi/H8r6CcJl_wA/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARgcIDkofzAP&rs=AOn4CLCnqk-9vrhdh-IcLL7xEZof5ZR_nw',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 38,
    id: '7AkhC_BFKCU',
    type: 'video',
    title: '#(인기급상승동영상)콩나물 매번 삶고 무치지 마세요 콩나물 김치 담아서 냉장고 두고 두고 시원하게 드세요 #1인식사',
    channel: '주부나라',
    timeAgo: '4년 전',
    views: '조회수 2,833,267회',
    viewsNum: 2833267,
    videoUrl: 'https://www.youtube.com/watch?v=7AkhC_BFKCU',
    thumb: 'https://i.ytimg.com/vi/7AkhC_BFKCU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBVBuKyzfmru6ruS25ZTjxhiIM11Q',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 39,
    id: 'LQEUbeo6biw',
    type: 'shorts',
    title: '문 열리자마자 \'휙!!\'…지하철 승객 다 살린 순발력 #JTBC #Shorts',
    channel: 'JTBC News',
    timeAgo: '3주 전',
    views: '조회수 993,860회',
    viewsNum: 993860,
    videoUrl: 'https://www.youtube.com/shorts/LQEUbeo6biw',
    thumb: 'https://i.ytimg.com/vi/LQEUbeo6biw/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARgTIFkofzAP&rs=AOn4CLCgX1Gof_HilTBYMdK5WWSYZbGzNg',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 40,
    id: 'XzKPenkVBeE',
    type: 'video',
    title: '\'잠이 보약\' 매일 푹 잤는데?…새로운 연구 결과 나왔다 / SBS / 뉴스딱',
    channel: 'SBS 뉴스',
    timeAgo: '1년 전',
    views: '조회수 2,779,890회',
    viewsNum: 2779890,
    videoUrl: 'https://www.youtube.com/watch?v=XzKPenkVBeE',
    thumb: 'https://i.ytimg.com/vi/XzKPenkVBeE/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDF5UjB98SAMHATAvjwBW2jmnzkvw',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 41,
    id: 'Tz14FFObpH8',
    type: 'shorts',
    title: '오싹오싹 니니모가 어떻게 변할까? 😈 #shorts',
    channel: '호기! 핑크퐁 - 놀면서 배워요',
    timeAgo: '1일 전',
    views: '조회수 68,624회',
    viewsNum: 68624,
    videoUrl: 'https://www.youtube.com/shorts/Tz14FFObpH8',
    thumb: 'https://i.ytimg.com/vi/Tz14FFObpH8/hq720.jpg?sqp=-oaymwE2CNAFEJQDSFXyq4qpAygIARUAAIhCGABwAcABBvABAfgBtgiAAoAPigIMCAAQARhJIDgofzAP&rs=AOn4CLCEFcaG26Y35dhz81ilnE1vWe9vyQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 42,
    id: 'cbkbtbD8PvE',
    type: 'video',
    title: '와! 이런방법이! 생활이 편리해지는 생활꿀팁/아이디어',
    channel: '태양우주맘',
    timeAgo: '4년 전',
    views: '조회수 2,477,249회',
    viewsNum: 2477249,
    videoUrl: 'https://www.youtube.com/watch?v=cbkbtbD8PvE',
    thumb: 'https://i.ytimg.com/vi/cbkbtbD8PvE/hq720.jpg?sqp=-oaymwEgCNAFEJQDSFXyq4qpAxIIARUAAIhCGAFwAcABBrgC8xg=&rs=AOn4CLA6vY4cHGmvLTlodCHSdDvzDMyFQA',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 43,
    id: 'HtuiNaPgChE',
    type: 'shorts',
    title: 'BTS (KOREA) 🇰🇷 vs Harry Styles (UK) 🇬🇧 - Trending Top Globally!! #shorts',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 898회',
    viewsNum: 898,
    videoUrl: 'https://www.youtube.com/shorts/HtuiNaPgChE',
    thumb: 'https://i.ytimg.com/vi/HtuiNaPgChE/frame0.jpg',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 44,
    id: '80EYwpdvMac',
    type: 'video',
    title: '[레전드] 웃고 삽시다! 듣고 있으면 웃음 + 감동이 있는 강연 | #재미있는 #세바시 #배움은 #덤',
    channel: '세바시 강연 Sebasi Talk',
    timeAgo: '1년 전',
    views: '조회수 2,207,409회',
    viewsNum: 2207409,
    videoUrl: 'https://www.youtube.com/watch?v=80EYwpdvMac',
    thumb: 'https://i.ytimg.com/vi/80EYwpdvMac/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBObDTjQF7wDNztWQWp1Mpm5hdoOA',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 45,
    id: 'ndBa2JbXpAA',
    type: 'shorts',
    title: '이케아 직원들도 몰래 사 간다는 레전드 도마 😱 #공간활용 #꿀팁 #살림꿀팁 #이케아 #좁은집인테리어  #쇼츠 #살림초보',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 835회',
    viewsNum: 835,
    videoUrl: 'https://www.youtube.com/shorts/ndBa2JbXpAA',
    thumb: 'https://i.ytimg.com/vi/ndBa2JbXpAA/frame0.jpg',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 46,
    id: 'bFzO509IPko',
    type: 'video',
    title: '[오늘 이슈] RM의 ‘갓’ 인터뷰 “식민지였던 한국이 성공한 이유” / KBS 2023.03.14.',
    channel: 'KBS News',
    timeAgo: '3년 전',
    views: '조회수 2,015,331회',
    viewsNum: 2015331,
    videoUrl: 'https://www.youtube.com/watch?v=bFzO509IPko',
    thumb: 'https://i.ytimg.com/vi/bFzO509IPko/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATigFHsCH7nNjzSGGQvi1KCUSOlQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 47,
    id: 'VqAMet_qgxQ',
    type: 'shorts',
    title: 'AI 맞춤형 제품 인기 #shorts',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 502회',
    viewsNum: 502,
    videoUrl: 'https://www.youtube.com/shorts/VqAMet_qgxQ',
    thumb: 'https://i.ytimg.com/vi/VqAMet_qgxQ/frame0.jpg',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 48,
    id: '3RbRyHcyI2s',
    type: 'video',
    title: '1탄-7탄 생활꿀팁 모음📚한번 알면 평생 편한 소소한 꿀팁 36가지!!',
    channel: 'YummyAt12시에맛나요',
    timeAgo: '5년 전',
    views: '조회수 1,981,382회',
    viewsNum: 1981382,
    videoUrl: 'https://www.youtube.com/watch?v=3RbRyHcyI2s',
    thumb: 'https://i.ytimg.com/vi/3RbRyHcyI2s/hqdefault.jpg?sqp=-oaymwEgCOADEI4CSFXyq4qpAxIIARUAAIhCGAFwAcABBrgC8xg=&rs=AOn4CLDbbgEu-kgpurIBBT-hzVbMC2vERQ',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 49,
    id: 'BUCLdq_jgps',
    type: 'shorts',
    title: '[라이브오늘_화제신속배달] BEST 엄지척 #shorts',
    channel: 'YouTube Shorts',
    timeAgo: '최근',
    views: '조회수 430회',
    viewsNum: 430,
    videoUrl: 'https://www.youtube.com/shorts/BUCLdq_jgps',
    thumb: 'https://i.ytimg.com/vi/BUCLdq_jgps/frame0.jpg',
    tags: ['전체'],
    period: 'month'
  },
  {
    rank: 50,
    id: 'K3PDRB9R-YI',
    type: 'video',
    title: '- 노부부의 한입만- (컬투쇼 레전드사연 애니메이션) by YOUTOO(유투) (KOR sub)',
    channel: 'YOUTOO - 유투 애니메이션 -',
    timeAgo: '3년 전',
    views: '조회수 1,661,995회',
    viewsNum: 1661995,
    videoUrl: 'https://www.youtube.com/watch?v=K3PDRB9R-YI',
    thumb: 'https://i.ytimg.com/vi/K3PDRB9R-YI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCe2dFAevOysvo2mo1D0-W5eAQkwQ',
    tags: ['전체'],
    period: 'month'
  }
];

// 기간별 맵핑 객체
window.VIRAL_SHORTS_BY_PERIOD = {
  today: window.VIRAL_SHORTS_TODAY,
  week: window.VIRAL_SHORTS_WEEK,
  month: window.VIRAL_SHORTS_MONTH
};

// 기본 호환성 데이터셋 (당일 기준)
window.VIRAL_SHORTS_50 = window.VIRAL_SHORTS_TODAY;